### ISSUE TITLE
Examples don't render on MacOS 10.14.X until resize

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/amethyst#1036]
Opening this issue to track the upstream changes that need to be in place to fix this issue. Reference #972 for further detail. Currently, there is a workaround in place to resize the window post creation, once the upstream fixes are in place we can remove this workaround

**Comment by azriel91** [comment]
Workaround for this issue was done in https://github.com/amethyst/amethyst/pull/1026.

#1131 *potentially* fixes this, but https://github.com/tomaka/glutin/issues/1069#issuecomment-439658263 says maybe not.
Can someone with OS X check if it did? Probably have to revert the workaround from #1026 to conclusively test.

**Comment by LucioFranco** [comment]
@azriel91 I've opened a PR that reverts the original fix for this, I've tested it and it works.
