### ISSUE TITLE
UiText doesn't take into account coloring method

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1109]
UiText currently ignores the selecting coloring method.

To replicate, simply check the ui example. You can change the color of a text and of a button to be the same, for example `(0.988, 0.537, 0.255, 1.0)` and you will see a pretty big difference.

### Task

Add the same coloring correction that is applied to normal textures to the text.

I set medium for the difficulty, but might be considered hard, because I *think* we gfx_glyph draw directly and we don't get anything we can modify on our side.

**Comment by jojolepro** [comment]
Was this fixed @Frizi ?

**Comment by jojolepro** [comment]
Maybe not stale? :P

**Comment by ishitatsuyuki** [comment]
From the perspective of a graphics programmer, using linear color space for everything feels perfectly intuitive. In addition to that, font hinting/AA is supposed to be done in linear space.

However, from the perspective of a designer, this surely feels awkward because we're used to deal with sRGB color values. It's just a preference... And we have to decide which we want to align to.

Anyway, we should be using `palette` types for taking UI colors, not the plain old array. That would make thing a lot clearer.
