### ISSUE TITLE
Concerns regarding performance throughout framework, future goals

### ISSUE THREAD

**Issue by bjadamson** [amethyst/amethyst#117]
Hi, I am concerned about the usage of mutex's and Arc's throughout the framework. There are also a lot of allocations (Box) that I can't remove (as a library user, I can since I'm also interested in submitting PR's to this project). Building a good framework that's easy to use is great, but can this data processing be done without explicit locks and mutexes?

https://github.com/amethyst/amethyst/search?utf8=%E2%9C%93&q=mutex
https://github.com/amethyst/amethyst/search?utf8=%E2%9C%93&q=arc
https://github.com/amethyst/amethyst/search?utf8=%E2%9C%93&q=box

I'm new to rust, and from a C++ background this surprises me. Game developers in general have avoided the STL for years for it's "slowness" (can't control allocations) so I doubt they wouldn't think twice about avoiding a framework that does allocations and locking out of their control.

I'm wondering about the future direction of amethyst, specifically if removing these arcs, mutexes, and Box allocations will ever be a priority. I understand _why_ they are used (or, atleast I think I do) and it's to allow communicating between threads, the shared data. It's a tradeoff that favors data parallelism over single-threaded performance. My point here is there are other trade-offs a developer can make when making a game or library.

One example would be ordering the processors manually so that none of the data is modified, but instead state changes are collected at the end of the frame, and processed all at once by a single thread. That strategy has different trade-offs than the current design of amethyst follows.

So my question is this, is amethyst going to consider this a serious issue in the future? I would love to help in this area, but the design seems to be growing in so many directions at the moment, that pinning these details down (you'll notice a general trend in issues I have been filing..  https://github.com/amethyst/amethyst/issues/88) seems intimidating.

Some reinforcement from the community on whether or not these issues make sense to tackle, and HOW to appropriately tackle them, would be greatly motivating. I really like the design of amethyst, I just don't want to see it ignored by those who want absolute control over the performance (I would really like to be able to do this).

Anyway, thanks for reading.

**Comment by ebkalderon** [comment]
@bjadamson You have some valid points here, and I agree that resolving them is definitely on the radar, especially the point about reducing our dependence on locks where possible. Indeed, the shared `Context` might need to slim down a bit to reduce contention and improve performace. For example, removing the renderer from the context and placing it directly into the `Rendering` processor where it belongs comes to mind.

However, given that most games are big blobs of shared mutable state, there is only so much we can do on this front. The idea that state changes are collected at the end of the frame and processed all at once with correct ordering was actually considered at one point during issue #10, but in the end the majority seemed to favor the mutex-based approach for various reasons, mostly due to inevitable latency.

Thankfully, Amethyst is still a young project and as such can afford to experiment on different approaches without really worrying (or perhaps caring?) about breakage until we find what works best.

**Comment by Xaeroxe** [comment]
We use next to 0 Arcs and Mutexes today so I'm closing this.
