### ISSUE TITLE
Design Pattern: Lazy Component Update + Animation

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#1182]
Hiya! Have got a pretty complex component update problem, and decided to post my thoughts in working out a clean and efficient way to solve it. What may eventuate from this:

* Nothing (except for my records).
* [specs](https://github.com/slide-rs/specs) gets new ideas / types to support such a case.
* Someone sees more alternatives, and potentially better ones when making a trade-off.

Note: some of the types in the problem statement are not yet mapped to ECS concepts, as they differ in the proposed solutions.

## Problem

* There exist objects with `SequenceId`, `Position`, `SpriteRender` `Interaction`, `Body`, and other *attributes*.
* Of those, `SpriteRender`, `Interaction`, and `Body` types are strictly tied to `SequenceId` and elapsed (logical) *time* since the sequence was switched to, and should change synchronously (frame-by-frame step interpolation).
* Objects may also be controlled by `ControllerInput`.
* Each tick, the `SequenceId`, `Position`, `..` attributes may update to new values, computed based on the values of these components **at the beginning of the dispatcher `update()`**:

    - `SequenceId`
    - `Position`
    - `ControllerInput`
    - `..` (other attributes not listed)

* However, the calculated *next values* for `SequenceId`, `Position`, and other components *may not* be used &ndash; if there is collision from an `Interaction` onto an object's `Body`, either or both the assailant and the assaulted may switch to a different `SequenceId`, `position` etc.
* The `SpriteRender`, `Interaction`, and `Body` types should switch based on the actual updated `SequenceId`, if any. Note: if there is no update, these types may still change, based on the elapsed (logical) time for the existing `SequenceId`.

Got all that? Nice 🕶.

So, here are some constraints to keep in mind:

* `FlaggedStorage` tracks insertions, modifications, and deletions of components. However, if we `join()` on any `WriteStorage<_>`, or call `write_storage.get_mut(entity)`, **even if we did not mutate the component, it is still marked as `Modified`**.

There are three parts to this problem:

1. Deciding which sequence update systems apply &ndash; "normal" (input + logical time), collision, potentially others (future possibilities).
2. Updating of attributes based on values at the beginning of dispatcher `update()`.
3. Determining what value to use for `SpriteRender`, `Interaction`, and `Body`.

#### 1A: Highest Priority System First

Subsequent systems skip processing for an entity if earlier systems have entered new values for the attributes of that entity.

**Pros:**

* Avoids unnecessary processing from subsequent systems.

**Cons:**

* More work to maintain &ndash; conditions for subsequent systems must be kept up to date.

**Notes:**

* "Power up" / "Buff" systems that operate on updated values from a particular earlier system are part of a "sequence update system group", and should use the same conditional logic to determine if it should or should not run.

#### 1B: Lowest Priority System First

Subsequent systems overwrite updated values for an entity.

**Pros:**

* Easier to maintain &ndash; only need to order systems.

**Cons:**

* Unnecessary CPU cycles consumed.

**Notes:**

* If a later system requests "no change" to an attribute value, it must explicitly write a "none" update, as an earlier system may have requested a change.

#### 1C: ??

---

#### 2A: Each attribute is a `Component`, `System` per "sequence update group"

* Each `System` from part 1 updates all attributes.
* `Component`s are accessed through `WriteStorage.get(entity)`, and if an update applies, it is updated either through `WriteStorage.get_mut(entity)` or ``WriteStorage.insert(entity, ..)``

**Pros:**

* No need to store the *last value* or *next value* separately.
* Easy precondition for part 3.

**Cons:**

* `Component`s are not updated in parallel.

#### 2B: Each attribute is a `Component`, `System` per `Component`

* Each attribute has its own `System` to calculate 
* `Component`s are accessed through `WriteStorage.get(entity)`, and if an update applies, it is updated either through `WriteStorage.get_mut(entity)` or ``WriteStorage.insert(entity, ..)``

**Pros:**

* `Component`s are updated in parallel.
* Easy precondition for part 3 using `FlaggedStorage`.

**Cons:**

* Either need to store the *last value* for each attribute, or *next value* separately.

    For each attribute for each entity:

    - If the `Last<T>` value is stored, each system will read the last value and compute / write the next value directly to storage.
    - For storing the *next value*, each system will read the current value, compute and write to a `WriteStorage<Next<T>>`, whose values will then be swapped at the end of the dispatcher's `update()`.

* Attribute value invariants must be manually upheld.
* Memory usage doubles for each attribute.

**Notes:**

* Doubling the memory is necessary to achieve parallelism. If we do not need parallel updating of attributes, then perhaps 2A more appropriate.

#### 2Z: Attributes are fields of a big `ObjectStatus` `Component`

**Pros:**

* Easy to update

**Cons:**

* Breaks benefits of ECS paradigm &ndash; locality / cache utilization of adjacent data, addition of attributes without interface bloat.

---

### Part 3

In this section, `Animation` refers to the type provided by `amethyst_animation`.

Since `SpriteRender`, `Interaction`, and `Body` are all tied to the `SequenceId`, we can use the `amethyst_animation` crate's capabilities to mutate their values by constructing `Animation`s with our own animation types.

#### 3A: `Animation` per attribute, `FlaggedStorage` to determine `Animation`s to swap

* `ComponentEvent`s from the `SequenceId` storage will determine which entities' will have anmations stopped and started.
* The *last value* of `SequenceId` attribute needs to be tracked, because we need it to `abort()` the animation in the `AnimationControlSet`. So even if we do not use 2B, this attribute will still be tracked.

**Pros:**

* Easier to add / remove individual animated components (ECS style?)

**Cons:**

* More wiring code needs to be written. (potentially generated?)

#### 3B: `Animation` per attribute, comparison to determine `Animation`s to swap

Similar to 3A, but instead of using `FlaggedStorage` (which uses bitsets), we do the comparison ourselves.

#### 3C: Single `Animation` to update all attributes

??

#### 3D: Implement another "animation" system

??

---

Probably going with 1A, 2A, 3A. Was implementing 2B, but after listing out the pros/cons, 2A seems more viable. 3D might be something to visit down the line.

**Comment by azriel91** [comment]
> a dedicated system and componenttable that creates a memory packed set of parallel/sequenced/actions of updates

Please teach! What would you use to implement this kind of thing now? Can think of:

* 2A, parallelization over entities instead of components, and applying the mutations after the loop
* pausing "system groups" (potentially via #1146)
* dispatcher within a dispatcher (theory, in practice it might be messy)

What does introspectable mean?

**Comment by OvermindDL1** [comment]
> Please teach! What would you use to implement this kind of thing now?

Well back on my old engine it was just a mapping of entity's to handles, the handles pointing to a packed 'bag' vector, each action would probably be a `class enum` now in C++ parlance but was just a set of simple structs at the time, I think I had this for the basic types:
```
Handle int
TickType int
Name String
Variant Lot|Of|Things|Used|Everywhere|In|The|Engine
Parallel HandleList
Sequenced HandleList
HandleList Handle HandleList|-1
SetValue Name Name Variant
InterpolateToValue Name Name TickType InterpolateType Variant Variant
...etc...
```
I stored it all in a packed vector for easy `memcpy`'ing (I liked having instant save/loads even with literal millions of entities) but that's not a hard requirement of course.  Basically each 'type' of thing like Parallel, Sequenced, SetValue, etc... were just uniqued on an integer (Atom type actually), then had the following data (aligned to word sizes though for most things so the unique byte was actually an int32 or int64 most of the time).

But when the system ran over it then it just processed the 'top' element of each entity and would basically do these things:
```
switch(type) {
case "PAR"_atom32:
  Run each linked list of cons cells (the `HandleList` type) each,
  and if they 'finish' then remove them from the linked list of handles
  and if none are left then pop the PAR list
break; case "SEQ"_atom32:
  Run the first in the linked list in handles, if it finishes then
  run the next until one doesn't finish, when all finish then pop the SEQ
break; case "SET"_atom32:
  Lookup the named component and the named variable in that component and set
  it to the value that is in the variant (errors if wrong type match)
break; case "INTERP"_atom32:
  Lookup the named component and the named variable in that component and do a
  type-specific kind of fake spline'ing of the current value based on the start
  and end variant values based on the InterpolateType (like cubic spline or
  whatever)
break; ... few others
break; default: ...throw error...
}
```

The lookup I've described in other threads elsewhere in detail, but essentially my engine was built to be data and script driven (even though I personally did most of it in C++, it was great for modding though or on-the-fly code modifications for testing).  There was a 'tree' of elements via a linux'y style path (which you could bake-on-load for fast accessing) and you could drill down to anything there.  If you already had an entity handle then you could just just grab it's data via something like `getPath("/level/current/entities/").getPath(entity).getPath("/components").getPath(componentName).getPath(variableName).set(newValue)` or so (realistically you'd prebake a lot of that access so it would be a bit more code on more lines but a whole lot faster, and in C++ you could do direct access to make it even more efficient if wanted.  The component data was stored in large tables, not on the entities (entities were nothing but integers, a handle and a generational id packed into an int64 or int32 depending on how it was built).  Everything was built to be introspectable passing the global Variant (or VariantMap) type everywhere as a globally-accessible set of methods.

The animation system I didn't actually use a whole lot as I preferred game-driven movements in my little mini-game rather than pre-built animations, but it did get occasional use and it was efficient enough.  I never bothered multi-threading the actual loop that iterated over the entities even though I didn't have other systems running (this system could potentially access any component) just because I never had much that used it.  If I did I probably would have had the loop run in parallel as each entity was independently accessed in it easily enough but the system couldn't be run in parallel with others that access components.

**Comment by fhaynes** [comment]
Closing this as it seems to have been answered.
