### ISSUE TITLE
Figure out a strategy for dealing with generics & default resources

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1197]
Consider a case where a system `M` accesses a resource `R`. Resource `R` is generic over `G` and implementes `Default`. There's another system `S` which writes into `R`, however it does so with `G = Foo`, while `M` uses `G = Bar`.

* System `S` -> `R<G = Foo>`
* System `M` <- `R<G = Bar>`
* Resource `R<G>`, `R<G>` implements `Default`

If those system get added like this, `M` will try to read from the resource, which, however, only ever has the state given to it by `Default::default`. That means nothing happens and there's no error.

One example of this is the usage of `InputHandler<AX, AC>`.

### Custom setup handler

It's possible to use a custom setup handler for systems reading from the resource that require the resource was added. and warn otherwise. This requires the "producer system" to be added before.

### Implementing a custom `SystemData`

We could wrap `ReadExpect` and give additional logging in case the resource is missing.

### Leaving things as-is

This is also a possibility and means this issue can be resolved by documentation.

**Comment by Xaeroxe** [comment]
This might be an unpopular opinion but I actually don't care much for magic registration of both components and entities we have going on here.  It's made initialization much more difficult to grok than it should be and I'd prefer to return to manual registration.

**Comment by azriel91** [comment]
For the `InputHandler` case, I think `AX` / `AC` shouldn't be constrained to `Default`. There might be other cases where some applications *do* want different `R<G>`s where a default `G` makes sense `=/`. If it's possible to say, "if there's already a non-default parameter `R<_>`, you must opt-in to have the default `R<G>`", that would be "safer".

>magic registration of both components and resources
Would you prefer manual registration for both `Component`s and `Resource`s, or does one or the other have a stronger drive?

**Comment by Xaeroxe** [comment]
Everything used to be full manual.  Nothing existed if you didn't manually add it to the world.  I liked it that way, initialization felt more straightforward.  If something wasn't working there was a specific place I could point to in the code and say "add it here".  Now with everything being automatically registered the rules for when, why, and how something is added to the world aren't quite as obvious until you look at the internal machinery of the `setup` methods.

**Comment by Xaeroxe** [comment]
> For the InputHandler case, I think AX / AC shouldn't be constrained to Default.

Also, good, because they aren't.  Nowhere do we require this.

**Comment by azriel91** [comment]
> Nowhere do we require this.

🎉 #808. I'm old

**Comment by jojolepro** [comment]
I do like automated registration :3
For small projects it doesn't matter, but when you have 40 components it starts to help a lot.

**Comment by Xaeroxe** [comment]
It also causes problems much like this one, where a user registers two different resources because they didn't realize they had requested different types in their systems.  Also, sometimes a resource initialization is dependent on another resource, or at least it should be.

One good example of this is the `ReaderId`s we have floating around.  Because we don't have access to the `EventChannel` until `setup()` is complete we frequently have to wrap these in `Option`s.  If we took more control of the initialization process this wouldn't be the case.

Another example is resources that have to be initialized by the renderer, such as `ScreenDimensions`.  As a thread local system it's always initialized last, which causes problems for any system that requires the `ScreenDimensions` during `setup`.

All of these things can be worked around as we've demonstrated, but it produces a lot of unnecessary API warts to make it all so implicit.

Being explicit in this instance may be desirable.  I don't particularly mind that as a side effect large projects need to have large lists.

**Comment by Xaeroxe** [comment]
>One good example of this is the ReaderIds we have floating around. Because we don't have access to the EventChannel until setup() is complete we frequently have to wrap these in Options. If we took more control of the initialization process this wouldn't be the case.

I've resolved this by moving `ReaderId`s into resources in #1203

**Comment by fhaynes** [comment]
@torkleyy is this still relevant?

**Comment by fhaynes** [comment]
Closing due to age, lack of activity, and resolution by @Xaeroxe the Great
