### ISSUE TITLE
Paused systems cause memory leaks in `EventBuffer`

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1204]
Events must be read every frame, but paused systems don't do that and will thus cause the `EventChannel` growing.

This is a blocking issue for 0.10.

**Comment by udoprog** [comment]
So I'm gonna clarify why I don't think this is a blocking issue.

This is a known footgun of using EventChannel: passive `ReaderId`'s causes the channel to grow indefinitely.

To me there is nothing special about a paused system that causes this behavior. Paused systems are specialized systems that "do nothing". In the absence of this mechanism users wanting to build something that "pauses systems" would be facing the same set of problems. If they forget to consume the `ReaderId` they would be leaking memory.

AFAICT, this is also the case for the conventional way of pausing systems today: using a separate dispatcher without dispatching it.

So for this reason I don't think we should treat Pausable systems as a blocker for 0.10.

But mid-term we should come up with a pattern for building event channels that doesn't have these properties. But I still don't think this is a blocker since it's a known caveat already.

**Comment by torkleyy** [comment]
> AFAICT, this is also the case for the conventional way of pausing systems today: using a separate dispatcher without dispatching it.

Okay, that makes sense. I'm fine with closing this issue as soon as there's documentation in place pointing this out.

**Comment by fhaynes** [comment]
Closing this as it is done
