### ISSUE TITLE
Book: Improve documentation about what EventChannel is (single vs multi producer)

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1210]
It should say "multi producer" because you can write events from as many systems as you want to.

**Comment by Xaeroxe** [comment]
No, because you can't write events from as many systems as you want to **simultaneously**.  That's the point of that distinction.

**Comment by torkleyy** [comment]
I guess that's true, but I still see it as "multi producer". If you insist on the wording, maybe we can still clarify it?

**Comment by Xaeroxe** [comment]
Yeah a clarification would be better I think.

**Comment by marot** [comment]
To my understanding, the implications of writing events are the same as writing to component storages since they use the same synchronization primitives (`Write`). I'm not sure why the distinction is necessary here. Are there any real-world examples where using multiple producers would lead to a significant performance loss?

**Comment by jojolepro** [comment]
This issue should probably be closed. Passing a single threaded writer around as a resource does not make it a multi producer. To be a multi producer, you at least need some type of write handle that you can copy around. Here, we pass the single event channel instance around to write to it.

@marot yes its bad for performance to have multiple systems writing to a single event channel. Exactly the same performance impact as having multiple systems writing to the same component type in fact.
