### ISSUE TITLE
Incorrect mouse position likely due to high DPI display

### ISSUE THREAD

**Issue by Sogomn** [amethyst/amethyst#1241]
`InputHandler::mouse_position` seems to return incorrect values on displays with high DPI.

![image](https://user-images.githubusercontent.com/40247521/49761846-68666580-fcc8-11e8-95f2-fe0d69ccfcaf.png)

The "Screen" size in the image is the window size. Top left of the window is still (0, 0) but the mouse position can be greater than the window bounds without leaving the window.

Occurs on a 3840x2160 28" (~157 DPI) monitor but only recently (since 0.10).

**Comment by jojolepro** [comment]
Thats my bad haha. Normally, screen size should be the physical pixel size. Are you getting this value from ScreenDimensions?

**Comment by ab0v3g4me** [comment]
I can actually confirm this as well. My mouse gets higher values than what the `ScreenDimensions` resource provides.

**Comment by Sogomn** [comment]
Yeah the window size came from `ScreenDimensions`.

**Comment by jojolepro** [comment]
I actually tested this and it was working just fine on my hidpi setup

**Comment by azriel91** [comment]
Not sure if relevant, but may be.
On my Ubuntu 16.04 laptop that is running Gnome 3.28 on X, the `ui` example draws a black window for the `0.10` release. That laptop has a 1.3333 hidpi factor. I did try setting it to 1.0 using `WINIT_HIDPI_FACTOR=1.0`, but it didn't do anything.

**Comment by Sogomn** [comment]
The screen dimensions are correct for me tho. The They are the values I have in my `display.ron`.

**Comment by ab0v3g4me** [comment]
Mine aren't due to Wayland (unless that's the problem). The problem of mine happens in fullscreen so there is no border and i guess the dimesnions should be the same as the screen resolution.

**Comment by Sogomn** [comment]
Did some more testing on a different device and it here it seems the window size isn't accurate. It's set to 1280x720 in the `display.ron` but the window fills the entire screen (1920x1080). 96 DPI monitor.

**Comment by jojolepro** [comment]
The dpi setting is in ScreenDimensions by the way, if you can check what it says.

**Comment by jojolepro** [comment]
Normally you should be getting the physical mouse position as well as the physical window size. I'll test on my laptop(hidpi) to make sure the results are valid.

**Comment by jojolepro** [comment]
Okay its clearly broken again for some reason...

**Comment by jojolepro** [comment]
Hello, can you test this and confirm if it works for you? Thanks! https://github.com/amethyst/amethyst/pull/1246

**Comment by Sogomn** [comment]
Yes, it does!

**Comment by yancouto** [comment]
Hello!

I think I've been hitting exactly this same issue. When using my large monitor, I see this in the logs:
```
Guessed window DPI factor: 1.25
```

And then the mouse position gets "out of sync" with the actual position on the screen by exactly this factor.

So I have a question: is the DPI scaling supposed to be transparent to us users when acessing mouse positions?
- If so, then this is probably a bug that needs fixing.
- If not, then how do I track the current DPI? (In order to take that into account.) I see `WindowEvent::HiDpiFactorChanged` when reading [this](https://docs.amethyst.rs/stable/amethyst_rendy/rendy/wsi/winit/dpi/index.html), and tried handling that event in my game state, but it does not show up. What is the correct way of tracking DPI?
