### ISSUE TITLE
Add Http & Future First Class Support

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1278]
Recently, I added CallbackQueue, which is used as a bridge between the async world of futures back to the Amethyst's threads. It can also be used for anything that is async, ie device events.

To make futures easier to use, I propose adding a syntax closely resembling the one used with world.exec:
```
world.future(|res: Write<'a, PulledRes>| { 
  http::get("http://whatever.com/myres").on_complete(|r| res = r);
}
```

I currently have some code samples working with Hyper (http client) and Tokio (futures). Those librairies are heavyweight: They have a lot of dependencies and take a lot of time to compile.

Do we want to:
A) Integrate them directly.
B) Integrate them directly, but behind a feature gate.
C) Delegate the integration to an external crate.

Also, is there someone who wants to take the lead on this issue/feature?

**Comment by udoprog** [comment]
> To make futures easier to use, I propose adding a syntax closely resembling the one used with world.exec:
> 
> ```
> world.future(|res: Write<'a, PulledRes>| { 
>   http::get("http://whatever.com/myres").on_complete(|r| res = r);
> }
> ```

I've done some investigating into futures. And one thing that became apparent to me is that resource management might be a bit of a pain point. For example, naively in the above example we would have to mutably lock `PulledRes` for writing for the entire duration of the future for this style to be safe. This is because the `res` object wraps a mutable reference to the underlying resource, which might otherwise be modified (and at worst moved) between the closure in `world.future(..)` being called and the future completing.

Is this what you'd expect as well?

**Comment by LucioFranco** [comment]
I think we would have to wrap the concept of a future for amethyst. I wonder if can have write just be `Write<Async<PulledRes>>`. Then it is the job of the engine to have the `&mut self` ref to the future. This way a system can think of a future available item as:

```rust
fn run(...) {
  match some_async {
    Async::Ready(val) => val,
    Async::NotReady => // do nothing,
  }
}
```

**Comment by jojolepro** [comment]
@udoprog not if you use something similar to CallbackQueue, because the resource will only be borrowed during the on_complete() part of the Future.

**Comment by fhaynes** [comment]
Closing this due to age and lack of progress. If there is interest, we'll put it on the roadmap.
