### ISSUE TITLE
Alpha channel not working for constant textures

### ISSUE THREAD

**Issue by mechaxl** [amethyst/amethyst#139]
As an example, I would expect that if I change the alpha channel values to `0.0` on these two lines, that the sphere example would just show a black screen:

https://github.com/amethyst/amethyst/blob/develop/examples/02_sphere/main.rs#L33

I changed them to this, and I can still see the sphere.

```rust
        ctx.asset_manager.create_constant_texture("dark_blue", [0.0, 0.0, 0.01, 0.0]);
        ctx.asset_manager.create_constant_texture("green", [0.0, 1.0, 0.0, 0.0]);
```

**Comment by mechaxl** [comment]
Also, it's entirely possible I'm not seeing something obvious, but I don't think I can add labels to this issue like it says to do here:

https://github.com/amethyst/amethyst/blob/develop/CONTRIBUTING.md

**Comment by Xaeroxe** [comment]
So alpha actually isn't implemented for anything but we'll fixing that when we address https://github.com/amethyst/amethyst/issues/357 I know this issue is technically older but when I search for transparency this issue doesn't come up and the other one does, so I'm going to close this as a duplicate.
