### ISSUE TITLE
[BUG] Audio playback problems

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#1440]
I know these exist but I don't know what they all are. So I wanted to open an issue where people could submit all of their problems with glitchy audio playback. Issues with the design and API are out of scope, as this issue is specifically looking to improve the low level audio interface. So, what are your problems with audio playback?

**Comment by jojolepro** [comment]
No sound at all.

Here's pong running and now outputting any sound into pulseaudio
![image](https://user-images.githubusercontent.com/4755185/53684768-9c599180-3cdf-11e9-8752-3d1cf9787b35.png)

My audio routes
![image](https://user-images.githubusercontent.com/4755185/53684775-ada29e00-3cdf-11e9-8b80-a3eb31aa15ba.png)

Audio settings
![image](https://user-images.githubusercontent.com/4755185/53684779-c8751280-3cdf-11e9-8f1e-313c163497a1.png)

This only happens using the alsa->pulseaudio->jack bridge.
All other applications that don't use rodio work just fine.
cpal works fine.

**Comment by azriel91** [comment]
> Hi, just started looking at amethyst. Is it a known issue that the audio on the pong example is crackly? At least on macOS. I couldn't find a github issue so thought maybe I'm just missing some system dependancy
>
> -- `@freebie` on discord

**Comment by ctsrc** [comment]
I am experiencing crackling both in the pong example and in my own game that I am working on. In my experience these sorts of issues are often related to the audio buffer. In particular, it probably means the buffer isn’t being filled fast enough.

**Comment by cjpearce** [comment]
On OSX with a recent macbook pro, I get significant crackling trying to play the pong example.

I think some of this may be due to the way amethyst_audio uses rodio (using `play_raw` rather than a pool of sinks or similar), but as far as the low level interface goes, it seems like one potential cause could be rodio itself. It looks like a lot of operations with rodio sinks - such as adding a source like we're doing here - involve acquiring a mutex. Almost any blocking on the audio thread could potentially lead to dropouts, so that seems like a place to investigate.

**Comment by Xaeroxe** [comment]
@cjpearce I think you're on to something here. The implementation for a Mutex differs between Windows and Unix systems, and we've never been able to reproduce this on Windows.

**Comment by calteran** [comment]
This bug is still occurring.  I reproduced it today using the Pong tutorial in Rust 1.53.0 and Amethyst 0.15.3.  Perhaps the Stale bot shouldn't be closing bugs that are simply awaiting programmer resources?

**Comment by kirusfg** [comment]
@jojolepro, have you been able to enable sound in Amethyst using PulseAudio ever since?
