### ISSUE TITLE
[NEW FEATURE] Implement Flat2D Pass for rendy

### ISSUE THREAD

**Issue by fhaynes** [amethyst/amethyst#1488]
# Summary

This pass needs to be implemented for Rendy: https://github.com/amethyst/amethyst/tree/master/amethyst_renderer/src/pass/flat2d

## How to Work on This

Please create a branch off of the `rendy` branch and submit PRs back to it. The work should be done in the `amethyst_rendy` crate.

**Comment by jaynus** [comment]
I'll be taking ownership of this, as I've been doing some rendy work as discussed with @Frizi and I've already got a good amount of experience with the 2D pass implementations.

**Comment by fhaynes** [comment]
Thank you! I sent you a collaborator invite, tis now assigned to you. =)

**Comment by azriel91** [comment]
Yo. not sure if this is the right time, but the current shader places the middle of the sprite at the origin.
It would be beneficial if this was configurable so that the `-0.5 * width, -0.5 * height` offset can be turned off.

Am not familiar if this should be something to implement in the pass / shader, so if it should be somewhere else let me know!

**Comment by Frizi** [comment]
@azriel91 The origin is controlled by "offsets" part of sprite definition in spritesheet. It is all relative to center, but you can control it per sprite.

**Comment by Frizi** [comment]
Also the pass is implemented, what's left right now is sorting by depth.

**Comment by Frizi** [comment]
And the depth sorting is done :)
