### ISSUE TITLE
[MAINTENANCE] Update pong_spritesheet.ron file for pong example

### ISSUE THREAD

**Issue by rmoretto** [amethyst/amethyst#1533]
## Description

Following the pong tutorial, most specific the [pong tutorial 2](https://www.amethyst.rs/book/master/pong-tutorial/pong-tutorial-02.html), I saw that the snippest  for the `pong_spritesheet.ron` file seems to be outdated, as it uses
two fields called `texture_width` and `texture_height` that I believe should be `spritesheet_width` and `spritesheet_height` as shown in this amethyst's book [page](https://www.amethyst.rs/book/latest/sprites/define_the_sprite_sheet.html]).

##### Current version:
```
(
    texture_width: 8,
    texture_height: 16,
    sprites: [
        (
            x: 0,
            y: 0,
            width: 4,
            height: 16,
        ),
        (
            x: 4,
            y: 0,
            width: 4,
            height: 4,
        ),
    ],
)
```
##### Proposed change:
```
(
    spritesheet_width: 8,
    spritesheet_height: 16,
    sprites: [
        (
            x: 0,
            y: 0,
            width: 4,
            height: 16,
        ),
        (
            x: 4,
            y: 0,
            width: 4,
            height: 4,
        ),
    ],
)
```

## Reason
Help keeping the documentation updated.

**Comment by azriel91** [comment]
ah, actually `texture_*` is the updated version. So the first link you're looking at is the `master` book, which is the unreleased bleeding edge version. The same page for the released book is https://www.amethyst.rs/book/latest/pong-tutorial/pong-tutorial-02.html#drawing

The second link is the `latest` book, which lines up with the released version. Just to summarize:

**latest** -- released (uses `spritesheet_*`)

* https://www.amethyst.rs/book/latest/pong-tutorial/pong-tutorial-02.html#drawing
* https://www.amethyst.rs/book/latest/sprites/define_the_sprite_sheet.html

**master** -- unreleased (uses `texture_*`)

* https://www.amethyst.rs/book/master/pong-tutorial/pong-tutorial-02.html#drawing
* https://www.amethyst.rs/book/master/sprites/define_the_sprite_sheet.html

part of me wants to rename either or both of them, because it's really easy to open both and consider them to be the same book.

@distransient maybe we do that as part of the 0.12 doc url changes
