### ISSUE TITLE
[BUG] AnimationSetPrefab does not work across state transition

### ISSUE THREAD

**Issue by aherrmann** [amethyst/amethyst#1559]
## Description

Take two `SimpleState`s: `Loading` for loading assets, and `Example` for executing the main game. If a prefab consisting of a `SpriteScenePrefab` and an `AnimationSetPrefab` is loaded in `Loading`'s `on_start` but the entity is only created in `Example`'s `on_start`, then the animation will not play. Instead, the sprite defined in the corresponding `SpriteScenePrefab` will be displayed.

## Reproduction Steps

1. Checkout [this commit from my amethyst fork](https://github.com/aherrmann/amethyst/commit/a18f98463df90720df2f85f65260b48eb4d03a22).
2. Execute `cargo run --example sprite_animation`

## What You Expected to Happen

The bats should be animated.

## What Actually Happened

The bats are not animated, but instead shown as still images.

## Screenshots and Logs

[trace.log](https://github.com/amethyst/amethyst/files/3133183/trace.log) generated at "trace" log-level.

## Your Environment

1. Operating System: openSUSE Tumbleweed
2. Operating System Version: 20190428
3. Version of Amethyst: 877e5412db486a9d13a4a523e1ee1a19edba2f12

## Additional Context

I discovered the issue when trying to add sprite animations following the `sprite_animation` example to a simple game project which separates the loading from the game state similar to the `renderable` example. I followed the documentation and examples as best as I could. In the likely case that I made a mistake, please let me know where. The `sprite_animation` example is, in my view, a bit artificial in that it performs both loading and the "main game" in a single state. It would be great if the example could be extended to separate loading and the main game state.

**Comment by barskern** [comment]
_Disclaimer: I'm rather new to the codebase, so I don't know if my assumptions are correct._

I've been trying this out locally, and it seems like the problem is that when you add the handle to prefab data to the entity, the underlying components are not directly added until after a few frames. This means that when you later try to join over entities and animation sets, there are actually no entities that have an animation set yet (you can verify this by adding a print statement inside the loop and you will see that it's never run).

As mentioned in the docs for the [Builder-trait](https://docs-src.amethyst.rs/stable/amethyst/prelude/trait.Builder.html#tymethod.with), when building enitites, the components may or may not exist before a call to `World::maintain`. 

> A common trait for EntityBuilder and LazyBuilder, allowing either to be used. Entity is definitely alive, but the components may or may not exist before a call to World::maintain.

I am not sure how to ensure that the prefab is transformed into actual components (naively calling `world.maintain` inside `on_start` did not work). However I have found a dirty way of solving this just to illustrate that the problem is not transfering the handle across states, but rather related to the late creation of components based on the prefab data. By rather moving the `world.exec` call into the `update` part of the implementation of `SimpleState` for `Example`, and then protecting it behind a counter so that it will add the animation after a few frames, I'm able to get the bats to animate. See example code below:

```rust

```

Further based on reading the source of `amethyst_assets`, it seems like it's the [`PrefabLoaderSystem`](https://docs-src.amethyst.rs/master/amethyst_assets/struct.PrefabLoaderSystem.html) which is responsible for turning `PrefabData` into `Component`s ([these lines](https://docs-src.amethyst.rs/master/src/amethyst_assets/prefab/system.rs.html#145-162)). Based on this I think this system has to be run a few times to successfully turn the handles into actual components.

**Comment by jojolepro** [comment]
delet stale

**Comment by JameeKim** [comment]
Hey, I'm experiencing a similar issue with this. I even tried putting the add_animation call to the update loop with a counter, and saw the "animation requested" log I put there, but still not working. I'll have to look into my code more to pinpoint the exact cause, but just letting ppl know.
