### ISSUE TITLE
Update to 0.4.0

### ISSUE THREAD

**Issue by Emilgardis** [amethyst/amethyst#158]
There hasn't been any updates on crates.io in a long time, and no TWIA or TMIA have been done.
What PR or features are we waiting on for a new release? And should it be a major, minor or fix bump?

In gitter, #133 and #144 was said to be what would be included in the new release, what happens now that #144 is closed?

**Comment by kvark** [comment]
I think it's a good time for TMIA as well as `0.3.2` release. I don't have permissions to publish it though, so pinging @ebkalderon once more. The situation around #144 is incomplete and needs us to seriously [talk](https://gitter.im/amethyst/engine?at=588686f1074f7be7630b16a6), but it doesn't have to go into the release.

**Comment by nchashch** [comment]
The engine changed a lot since `0.3.1` and there were some breaking changes (`Application` and `StateMachine` structs were changed, `amethyst_renderer::Frame` was split into `Pipeline` and `Scene`). I think it would make more sense to release `0.4.0`. SemVer doesn't prescribe how to deal with unstable versions. I suggest during unstable phase incrementing MINOR version when any breaking changes are introduced and PATCH version for any backwards compatible changes (both bug fixes and feature implementations). After stable 1.0.0 we can switch to standard SemVer rules.

Also I guess it would be nice to adopt a release schedule, maybe with a release each month (with an accompanying TMIA). Since it isn't possible to pull in the latest version of amethyst as a dependency with cargo and a lot of changes accumulate over time and we end up with an unwieldy change log (for example since `0.3.1` were added: windowing, rendering, config mechanism, transformation processor, asset manager, event handling support).

**Comment by kvark** [comment]
@nchashch yes, 0.4.0 makes more sense. The convention of bumping the minor version for 0.x.y is well established, if not within SemVer spec itself, then at least among the rust projects that use it.

**Comment by Emilgardis** [comment]
I agree with 0.4.0. There are some projects that use this type of modified SemVer spec, we should specify precisly how pre-1.0.0 bumps are done.
@LucioFranco has written the previous TWIA/TMIA (?), but he seems to be occupied with school for now.

**Comment by ebkalderon** [comment]
@amethyst/engine-devs Given the massive code churn the Amethyst codebase has seen since the past release, a 0.4.0 release on crates.io is most definitely in order. Anyone opposed to publishing the new release right now?

**Comment by LucioFranco** [comment]
@Emilgardis I am quite busy right now. But I am willing to help out if @ebkalderon or anyone else has the time to take the lead on writing the TMIA.

Overall I agree with a new release!

**Comment by Emilgardis** [comment]
cc #59, #165
https://github.com/Emilgardis/amethyst/tree/pre-0.4.0
If you want to contribute I suggest you do a PR on that branch, the idea is to limit PR noise on amethyst/amethyst.

**Comment by ebkalderon** [comment]
@amethyst/engine-devs Hey, I think we really should push out a new release. Right now, if possible. Doesn't matter whether there are still pull requests waiting in the queue, we are still in the 0.X.Y stage and therefore should be pushing out very frequent releases.

@Emilgardis Do you still want us to use your branch of the repo or should we open up a new one, given the flood of PR's being merged in the past few days?

**Comment by ebkalderon** [comment]
Alright, since there don't appear to be any objections, I'm game. I'm drafting up a new release right now!

**Comment by ebkalderon** [comment]
@amethyst/engine-devs Congratulations everyone, we are now 0.4! 😎 🎉
