### ISSUE TITLE
[BUG] `VERGEN_TARGET_TRIPLE` undefined

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1588]
## Description

The compilation of `amethyst` (987bba3d900d68b5216bf3624765d42a52fa6386) is failing with this error:

```
error: environment variable `VERGEN_TARGET_TRIPLE` not defined
   --> src/app.rs:487:31
    |
487 |         info!("Platform: {}", env!("VERGEN_TARGET_TRIPLE"));
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

## Reproduction Steps

1. Clone `master`
2. `cargo +stable build`

## Your Environment

1. OS: Fedora
2. Kernel: 5.0.9-200.fc29.x86_64
3. 987bba3d900d68b5216bf3624765d42a52fa6386

## Additional Context

It seems this is a regression caused by #1586, and happens exclusively on stable Rust.

**Comment by fhaynes** [comment]
Hmm, interesting. vergen is nothing this added in, I don't think

**Comment by fhaynes** [comment]
Hmm, can't repro this:
```
   Compiling amethyst_core v0.5.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_core)
   Compiling amethyst_assets v0.6.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_assets)
   Compiling amethyst_network v0.3.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_network)
   Compiling amethyst_renderer v0.10.1 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_renderer)
   Compiling amethyst_locale v0.4.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_locale)
   Compiling amethyst_input v0.6.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_input)
   Compiling amethyst_animation v0.5.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_animation)
   Compiling amethyst_controls v0.4.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_controls)
   Compiling amethyst_utils v0.5.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_utils)
   Compiling amethyst_audio v0.5.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_audio)
   Compiling amethyst_ui v0.5.0 (/Users/fletcher/Projects/amethyst/amethyst/amethyst_ui)
    Finished dev [unoptimized + debuginfo] target(s) in 5m 45s
DESKTOP-3A6L2R7:amethyst fletcher$ cargo +stable build
    Finished dev [unoptimized + debuginfo] target(s) in 0.72s
```

**Comment by torkleyy** [comment]
After a fresh build, I cannot reproduce this myself any more. Sorry for the noise!

**Comment by marot** [comment]
I encountered this in the CI: https://jenkins.amethyst-engine.org/blue/organizations/jenkins/amethyst/detail/PR-1587/9/pipeline/47
https://jenkins.amethyst-engine.org/blue/organizations/jenkins/amethyst/detail/PR-1587/11/pipeline/16

Not sure if that will go away too, should I reopen the issue?

**Comment by fhaynes** [comment]
I cleared the cache, and it seems to be building now. Will close this if it succeeds.

**Comment by marot** [comment]
@fhaynes Yep, I expected them. Thanks for fixing this.

**Comment by fhaynes** [comment]
No problem! Going to close this

**Comment by marot** [comment]
@fhaynes Sorry again :( There is another error: https://jenkins.amethyst-engine.org/blue/organizations/jenkins/amethyst/detail/PR-1587/16/pipeline/15

Are we sure it is not related to the changes of #1586? If the added code throws an exception because e.g. the CI is not allowed to write into the home directory, won't that cause `vergen` not to run?
I don't see anything related in the logs, but I'm not sure if errors would be visible.

**Comment by marot** [comment]
@jojolepro maybe it makes sense to revert #1586 for now? I'm not sure if bors failures are also related to this.

**Comment by Frizi** [comment]
If an exception is thrown, the whole build should fail anyway.  We can move that vergen code to the beginning, but it still should be investigated what's happening in there.

**Comment by azriel91** [comment]
`build.rs` expects to read input: https://github.com/amethyst/amethyst/blob/987bba3d900d68b5216bf3624765d42a52fa6386/build.rs#L60-L62

Theory (not yet confirmed):

* we get back an `io::Error`, with kind: [`WouldBlock`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.WouldBlock).
* `build.rs` fails to compile, and vergen code hasn't been executed
* `cargo` still continues building the main crate, but fails

Needs more investigation, but best practice is to not insert something interactive in something that is by default (and by design) non-interactive -- it breaks user assumptions, and can be very difficult to trace (why is this build/web service/.. timing out).

Trying to reproduce this with a non-interactive shell on windows, haven't succeeded yet.

**Comment by azriel91** [comment]
Breadcrumbs:

1. [`build.rs`](https://github.com/amethyst/amethyst/blob/987bba3d900d68b5216bf3624765d42a52fa6386/build.rs) should generate the `VERGEN_*` environmental variables, assuming it gets past the sentry permission checks.
2. Compilation should terminate if any error happens in `build.rs`.
3. Compilation does not terminate -- meaning there was no error. (do we trust this?)
4. There's a `stdin().readline()`, but it returns empty string (`""`) when run in a non-interactive shell.

    You can try this by inserting `panic!("stdin: `{}`", s);` into `build.rs`.

    ```
    error: failed to run custom build command for `amethyst v0.10.0 (D:\work\github\amethyst\amethyst)`
    process didn't exit successfully: `D:\work\github\amethyst\amethyst\target\debug\build\amethyst-49441742d274fb18\build-script-build` (exit code: 101)
    --- stdout
    May we collect anonymous panic data and usage statistics to help improve Amethyst? No personal information is collected or stored. [Y/n]:
    --- stderr
    thread 'main' panicked at 'stdin: ``', build.rs:64:5
    ```

5. `~/.amethyst/.sentry_status.txt` stores whether sentry is allowed. This is written to when the `amethyst` (root crate) is compiled. This is usually the string `false`.

<details>

<summary>Checking build agent (boring)</summary>

In both `stable` and `nightly` builds, we get two `target/debug/build/amethyst-<HASH>/` directories.

On `stable`:

* `/home/jenkins/workspace/amethyst_PR-1591/target/debug/build/amethyst-473ca17d438d8c11/`
* `/home/jenkins/workspace/amethyst_PR-1591/target/debug/build/amethyst-b0f1aae1b7137a86/`

On `nightly`:

* `/home/jenkins/workspace/amethyst_PR-1591@2/target/debug/build/amethyst-f59c838b0465e2f1/`
* `/home/jenkins/workspace/amethyst_PR-1591@2/target/debug/build/amethyst-96a8e35d3e8d8015/`

One of each's `crate-<HASH>` directories has an `output` file, which looks like this:

```bash
cat /home/jenkins/workspace/amethyst_PR-1591/target/debug/build/amethyst-b0f1aae1b7137a86/output
May we collect anonymous panic data and usage statistics to help improve Amethyst? No personal information is collected or stored. [Y/n]: cargo:rustc-env=VERGEN_SHA=974b7db6621c12c1705d499c8a6a4ec59120a1e2
cargo:rustc-env=VERGEN_BUILD_DATE=2019-05-10
cargo:rustc-env=VERGEN_COMMIT_DATE=2019-05-11
cargo:rustc-env=VERGEN_SEMVER=0.10.0
cargo:rustc-env=VERGEN_SEMVER_LIGHTWEIGHT=0.10.0
cargo:rustc-env=VERGEN_TARGET_TRIPLE=x86_64-unknown-linux-gnu
cargo:rustc-env=VERGEN_BUILD_TIMESTAMP=2019-05-10T23:29:47.547157391+00:00
cargo:rustc-env=VERGEN_SHA_SHORT=974b7db6
cargo:rerun-if-changed=.git/HEAD
cargo:rerun-if-changed=build.rs
```

---

`nightly` also has no `output` in one of its build output directories. I was going to say we can't conclude that that part is broken, but "what if `stable` just *happens* to fail first, and we don't see the failure from `nightly` because we already stopped because of `stable`?"

</details>

Local investigation tip, use this:

```bash
#! /bin/bash

# if this contains `i`, then you are using an interactive shell.
# B means expand braces.
# h means something about hashing, i forgot but it's not important.
echo $-

rm -f ~/.amethyst/.sentry_status.txt
rm -rf ./target/debug/build/amethyst-* ./target/debug/deps/libamethyst-*
cargo +stable build
```

---

Gonna stop here for today

**Comment by azriel91** [comment]
woo, solved the technical part in #1592. `print` was interfering with the environmental variables that `cargo` reads.
Switched it to `eprint`.

I'm *okay* with keeping that as a workaround (reluctant "okay"), but would rather not have a prompt in `build.rs` at all.

**Comment by azriel91** [comment]
another thing is perhaps storing the sentry permission inside the `target` directory, or maybe something similar to how cargo does it (`$repo_dir/.cargo/config`, or [others](https://stackoverflow.com/questions/46649992/where-can-i-find-cargo-config)) because it's possible that one would want some projects to have it on, and others off... but this is me over-engineering it. *\*ahem\** let's only go there when we need to.

**Comment by fhaynes** [comment]
I left the per-project config option out until we have a default project structure. We'll want an all-project permission and then overridable at the project level.

**Comment by torkleyy** [comment]
Seems to be fixed now.
