### ISSUE TITLE
[FEATURE MODIFICATION] Input types for amethyst

### ISSUE THREAD

**Issue by TimonPost** [amethyst/amethyst#1608]
## Feature

I'd like to have a modification to how input handling works. 

## Change

The change has to do with the fact that `InputHandler` takes in and returns `winit` key events from its functions. I think it would be useful, to make amethyst own her own own input types. This would be the basicly a copy of this [file ](https://github.com/rust-windowing/winit/blob/master/src/events.rs) copied over to amethyst with a conversion from winit types to amethyst types.

## Reason
I want this because now I need to have a dependency to `winit`, which is a pretty big one if I only need to know the pressed key or mouse. Also, the amethyst `winit` dependency is outdated, and now I need to have a reference to an outdated crate.
 
## Impact

We can keep the exact same api, same names as the once `winit` uses. The only changes the user needs to do are the imports from `winit::{VirtualKeyCode, MouseButton, ...}` to amethyst::input::{VirtualKeyCode, MouseButton, ...}.

## Additional Notes

Example of mouse button conversion to own type

```rust
/// Describes a button of a mouse controller.
#[derive(Debug, Hash, PartialEq, Eq, Clone, Copy)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum MouseButton {
    Left,
    Right,
    Middle,
    Other(u8),
}

impl From<winit::MouseButton> for MouseButton {
    fn from(button: winit::MouseButton) -> Self {
        match button {
            winit::MouseButton::Left => { MouseButton::Left },
            winit::MouseButton::Right => { MouseButton::Right },
            winit::MouseButton::Middle => { MouseButton::Middle },
            winit::MouseButton::Other(o) => { MouseButton::Other(o) },
        }
    }
}

```

**Comment by OvermindDL1** [comment]
Mouse buttons shouldn't be left/right/middle/other as that will not line up with all expectations.  It should just be a number index of the button starting at 0.  Some people with mice have their left/right swapped, touchpads use interactions to determine how to click, etc... etc...  Plus why the weird special left/right/middle instead of just matching to index 0/1/2 and keep consistency?  Having those be special means that you can't use the same action map code for everything and instead of have match out every single instance of it, which can get a bit painful.

**Comment by jojolepro** [comment]
IMO maintaining our own copy of all possible keys is pretty much unmaintainable. I'd rather reexport winit. As no work has been done on this yet and this is very low priority, I'll go ahead and close the issue. Feel free to reopen it if you want to discuss it more.
