### ISSUE TITLE
Extend window functionality

### ISSUE THREAD

**Issue by nulldatamap** [amethyst/amethyst#162]
Currently, very little window functionality is exposed. Functions like `set_title`, `set_cursor`, `set_cursor_position` and `set_cursor_state` would be very useful, plus information like whether the window has exclusive fullscreen or not.

The following approaches have been brought up on Gitter:
1. Extend the current interface of GfxDevice
2. Having the InputHandler a reference to window and integrate the cursor management
3. Directly expose the window as resource
4. Have a proxy window resource, which is checked by the engine loop and updates the backend window accordingly

**Comment by Emilgardis** [comment]
Window as a resource seems to most viable way to approach this AFAIK, it mimics the current way we do transforms, camera and input handling. Cursor management should be provided there aswell.

**Comment by nchashch** [comment]
I don't think we can directly expose window as a resource, since it isnt `Send + Sync` and different platforms provide different `Window` types (for example `gfx_window_glutin` provides a different type than `gfx_window_dxgi`).

So probably exposing a proxy window resource is a way to go (there is already `ScreenDimensions` resource providing width and height of the window, I guess we can rename it to, say `Window`, and expose all the other things).

**Comment by nulldatamap** [comment]
If we're going to do proxying with things like mouse position, then implementing this should probably be done together with https://github.com/amethyst/amethyst/issues/104.

**Comment by Emilgardis** [comment]
#104 is already implemented, it is open because of the requests from gitter.
@nchashch That's what I meant, ofc exposing the gfx-rs type wouldn't work as expected.
What functions should there be?

- getters/setters for window size
- getters/setters for window properties (title, priority/visibility, frame) 
- getters/setters for mouse position
- getters/setters for mouse type
- getter/setter for mouse visibility

Are all of these possible on all platforms?

The getters/setters can be combined into a `modify` function that takes an `Fn<(WindowProperty*)>`.

**Comment by Xaeroxe** [comment]
This issue is slightly outdated but mostly resolved by #387 so I'm going to close this.
