### ISSUE TITLE
[BUG] Input axes MouseWheel only outputs (0.0)

### ISSUE THREAD

**Issue by mralve** [amethyst/amethyst#1627]
## Description
Mouse wheel is not outputting the users scroll

## Reproduction Steps
In bindings file bind the mouse wheel to a axes.
(
  axes: {
    "scroll": Emulated( pos: MouseWheel(ScrollUp), neg: MouseWheel(ScrollDown)  ),
  },
)

## What You Expected to Happen

Scroll up = outputs (1.0)
Scroll down = outputs (-1.0)

## What Actually Happened

This only outputs (0.0)

## Your Environment

1. Operating System
Linux, Arch XFCE4
3. Version of Amethyst
6bdc329

**Comment by Xaeroxe** [comment]
Due to the fact that the mouse wheel scroll button is never actually "pressed" for a duration, merely pressed and then immediately released, this expected behavior can only be produced by lying about what the operating system reports. You'll notice engines like UE4 and Unity behave similarly.

That being said, I understand why this is annoying and we should try to do better. I'll think about it.
