### ISSUE TITLE
[FEATURE MODIFICATION] Make amethyst_rendy use the `Float` type

### ISSUE THREAD

**Issue by bonsairobo** [amethyst/amethyst#1709]
## Feature

amethyst_rendy module

## Change

Use the `Float` type instead of `f32` in places that make sense.

## Reason

It's hard to use things like `camera::Projection` and `DebugLinesComponent` that take vector types with `f32` components.

## Impact

You will probably have to convert the `Float`s to `f32`s before giving them to `rendy` APIs.

**Comment by bonsairobo** [comment]
It would also be really nice to have `From` trait implemented for converting between vector types with different float types.

**Comment by Frizi** [comment]
Both mentioned types are directly being used as a datra source for GPU uploads, where types indeed must always be `f32`. Adding conversions in the renderer for those would add potentially significant per-frame performance impact. There is no reason to use `Float` there.

`From` is impossible to implement on `Vector`/`Matrix` types due to orphan rules. We can't implement std trait for type from external crate (`nalgebra` in this case).

**Comment by bonsairobo** [comment]
I see, the expected way to deal with this is using `amethyst::math::convert`. I was looking around in the Discord, and people were doing some other less than ideal conversions. Maybe there should be more documentation about `Float`.

I would be surprised if converting vectors from `Float` to `f32` incurred any performance penalty. I'd expect the dispatch to be monomorphized, and converting from a `Float` to `f32` is just a reinterpret cast (since it's just a newtype). I would need to see the assembly though.
