### ISSUE TITLE
[BUG] Rendering artifacts

### ISSUE THREAD

**Issue by Attil** [amethyst/amethyst#1727]
## Description

Whenever I run some code using the new renderer, there are no errors reported but the engine, but the rendered image is full of artifacts (See [screenshot](https://imgur.com/a/ey5t3EX)).

## Reproduction Steps

```
cargo run --example pong --features "vulkan"
```

## What You Expected to Happen

I expected to see pong game like in previous version of Amethyst.

## What Actually Happened

I've seen [artifacts](https://imgur.com/a/ey5t3EX) with no error messages. A window was created and there was some movement in upper part, so probably some rendering was being done, just incorrectly applied to the window or something?

## Screenshots and Logs

[Screenshot](https://imgur.com/a/ey5t3EX)
[Logs](https://pastebin.com/qd4YxLKy)

## Your Environment

OS: ArchLinux
Wayland - Sway
Vulkan
AMD Radeon R7 M370 2 GB

Version: Commit # f2bd250c2047826caeb933b87ef6d9f1939e9018

## Additional Context
The in-game systems seem to work fine, debug messages and scoring is being correctly counted.

**Comment by Frizi** [comment]
First question is what drivers are you using?

Also if you are able to, i'd really appreciate some debugging on your end using [renderdoc](https://renderdoc.org/).

To capture a frame, download renderdoc and run "qrenderdoc", then in "Launch Application" you have to select
- "Executable Path" to "AMETHYST_ROOT/target/release/examples/pong" (or "debug" instead of "release" to run debug build)
- "Working Directory" to amethyst root
- in "Environment Variables" set "CARGO_MANIFEST_DIR" to amethyst root.

In my setup (on windows) it looks like that, your path will be unixy ofc
![image](https://user-images.githubusercontent.com/919491/59609697-27885700-9118-11e9-87f5-8557c9ea9e11.png)

Then you can Launch it and inspect how the rendered frame looks like at various stages. Are textures looking all right? I can assist to get some meaningful data from that once you've got it running.

**Comment by Attil** [comment]
Hi, thanks for the response :)

I am using `amdgpu` drivers.

```
$ lspci -k
...
03:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Mars [Radeon HD 8670A/8670M/8750M] (rev 81)
	Subsystem: Lenovo Mars [Radeon HD 8670A/8670M/8750M]
	Kernel driver in use: amdgpu
	Kernel modules: radeon, amdgpu
```

Before that I was using `radeon drivers`, however Amethyst didn't start in that case, failing to find physical devices.

About the renderdoc:
I tried to start the pong example using it, but it failed with the following error (I've set up `RUST_BACKTRACE` to `1`):
[Log](https://pastebin.com/AED1xbii).
The `VK_KHR_wayland_surface` bit seems interesting.

I managed to run the app just fine (although with the artifacts I've mentioned earlier) by issuing command line
```
CARGO_MANIFEST_DIR=`pwd` target/debug/examples/pong
```

**Comment by Frizi** [comment]
It's not the first time we have problems with radv drivers on linux, notably that line speask for itself
```
WARNING: radv is not a conformant vulkan implementation, testing use only.
```
Make sure that you actually have your drivers up to date, they release those quite regularily now with a lot of churn on RADV.

Also, clearly renderdoc didn't managed to get wayland WSI to cooperate. If driver update wasn't enough, try with [renderdoc nightly](https://renderdoc.org/builds) maybe.

**Comment by Attil** [comment]
Thanks for the reponse!

I've tried the renderdoc build from git, same issue sadly.

My mesa version is `19.0.6-1`, which is also the `amdgpu` version if I understood things correctly. I'll try the `19.2` nightly version and check if it fixes the issue.

**Comment by jaynus** [comment]
This tearing looks like a Vsync tearing issue which is a pretty global issue with some Vulkan drivers. Have you tried playing with those settings?

**Comment by Attil** [comment]
I've tried `19.1` mesa, it didn't help (git version didn't compile).

Thanks for the Vsync suggestion. How do I configure it from Amethyst? I've noticed previous versions had this field in [`DisplayConfig`](https://github.com/amethyst/amethyst/blob/master/amethyst_window/src/config.rs) struct, but it seems since removed.

**Comment by torkleyy** [comment]
Oh, that seems like an oversight to me.

**Comment by cyberj** [comment]
@Attil Maybe it's linked with #1830 can you try mesa 19.1.3 ?
