### ISSUE TITLE
[MAINTENANCE] Stepping

### ISSUE THREAD

**Issue by AndreaCatania** [amethyst/amethyst#1735]
## Description

While looking at the stepping function, I've noticed that we don't have a fail safe algorithm for the fixed update stepping.
This mean that if we run amethyst and a process takes too much to process something the fixed update is called multiple times due to the large time step which again will increase the time step of next frame which mean again more fixed update calls and so on in an infinite loop.

A good thing would be have a fail safe algorithm that limit the fixed updates to something like 8.

However if the fail safe algorithm exist, worth mention it anyway, but I would like to see it so I  will appreciate if you tell me where I can find it.

**Comment by jaynus** [comment]
This is by design. If your fixed update is taking too long, then you are inherently breaking the design of your game. A fixed update is not inherently a guarantee that an update will run every X seconds - it is a guarantee that the a simulation will be ran at every N interval. 

This means that even if your simulation runs slower, or faster, you will always get a simulation step at N interval. This is also why we use accumulators instead of strictly time comparisons. An accumulator allows us to run N simulation steps for every X time, regardless of actual run time. 

If your simulation is inherently way too slow for such a operation, then your design is inherently flawed and you should reconsider your execution and/or step interval. I do not believe it is in the best interest of the engine to soften the blow for these situations, as that will then soften guarantees and may cause issues down the line with other simulations.

More reading: http://web.archive.org/web/20190403012130/https://gafferongames.com/post/fix_your_timestep/

**Comment by AndreaCatania** [comment]
This is not what I mean, probably my explanation is not enough detailed so let me enrich it.
But let's assume that we are working with integers rather than floats to make my life easier :)

-----

We have the following execution process:
 - Normal process that takes **1 second**
 - Fixed process that take **1 second** per each execution. The fixed time is set at **1 second**

The first step we have a scenario where the actual DT is 0 so only the Normal process is executed:
**1 +** Normal process
= _1 Second Execution time_

The second step we have the DT to 1 so:
**1 +** Normal process
**1 +** Fixed process
= _2 Second Execution time_

The result is that the DT of the next frame is 2 so:
**1 +** Normal process
**1 +** Fixed process
**1 +** Fixed process
= _3 Second Execution time_

The result again is that the DT of the next frame is 3 so:
**1 +** Normal process
**1 +** Fixed process
**1 +** Fixed process
**1 +** Fixed process
= _4 Second Execution time_

The result again again is that the DT of the next frame is 4 so:
**1 +** Normal process
**1 +** Fixed process
**1 +** Fixed process
**1 +** Fixed process
**1 +** Fixed process
= _5 Second Execution time_

And so on....

As you can see without a fallback algorithm that stop it the performances of your application keep degrading because the fixed algorithm is executed over and over again in the same frame.

Usually in real life this kind of scenario happens when you have a bigger DT due from model loading, or window switching. So a single big DT may execute many fixed process triggering the above scenario where you are forced to shutdown your game and reopen it.

**Comment by jojolepro** [comment]
not stale

**Comment by distransient** [comment]
Since this is going stale anyways, closing this *for now* in lieu of this [forum post](https://community.amethyst.rs/t/the-clocks-thread-time-keeps-on-ticking/1184) where we may discuss this issue as well as others with our clock API's.
