### ISSUE TITLE
[BUG] Renderer use Srgb color types

### ISSUE THREAD

**Issue by ishitatsuyuki** [amethyst/amethyst#1903]
## Description

Renderer components including (but not limited to) Tint uses `Srgba` (or `Srgb`) types from `palette`. This does not match Vulkan's behavior to my understanding.

## What You Expected to Happen

The types should have been `LinSrgba` (or `LinSrgb`). Vulkan only uses sRGB as a storage encoding (for floating point); any color processed in code are linear.

**Comment by ishitatsuyuki** [comment]
not stale

**Comment by ishitatsuyuki** [comment]
not stale

**Comment by LechintanTudor** [comment]
We should use `Srgba` types for user-facing code but convert them to `LinRgba` when sending the data to the renderer. What we are doing now is sending data as `Srgba` but interpreting it as `LinRgba` in the shaders which makes colors overly bright.

**Comment by Blisto91** [comment]
@LechintanTudor Has this been fixed by your [PR #2314](https://github.com/amethyst/amethyst/pull/2314)?

**Comment by LechintanTudor** [comment]
@Blisto91 Yes

**Comment by Blisto91** [comment]
@LechintanTudor Roger thank you!

Just want to double check before I close because I don't have much knowledge on the subject. :) 
Op said ```Renderer components including (but not limited to) Tint```
Were there other things besides ``Tint`` that needed a fix or did the PR pretty much cover it?

**Comment by LechintanTudor** [comment]
There are other places where the color space is unspecified and it's assumed to be linear RGBA (e.g. when color is passed as a `[f32; 4]`). Tint was a problem because it explicitly used sRGBA and treated it like linear RGBA without performing any conversions. In my opinion we should use sRGBA everywhere as it matches the way the human eye perceives light and colors and leads to better results.

**Comment by jojolepro** [comment]
according to comments, it seems this is fixed.
