### ISSUE TITLE
[FEATURE MODIFICATION] Use reversed-Z and infinite zFar to improve depth precision

### ISSUE THREAD

**Issue by ishitatsuyuki** [amethyst/amethyst#1914]
## Feature

Reversed-Z and infinite zFar are techniques that increases the precision of a projection matrix and helps with z-fighting. Both are described in [this article](http://dev.theomader.com/depth-precision/).

## Change

The Amethyst `Projection::perspective` implementation should be changed to use it.

The renderer will use have the depth comparison function reversed.

## Impact

Renderer changes, and a small API change for specifying infinite zFar (`far` becomes `Option<f32>`).

**Comment by ishitatsuyuki** [comment]
not stale

**Comment by joonazan** [comment]
I am interested in this.

I think having no far clipping plane would be a good default, as otherwise a scene may render as if it was empty due to the far clipping plane.

**Comment by distransient** [comment]
Would you be interested in writing a PR implementing this?

**Comment by joonazan** [comment]
Yes. My job would even pay for it.

I am going on vacation soon, so I will look into this more in January.

**Comment by distransient** [comment]
Awesome! Feel free to ping us on discord anytime you have questions.

**Comment by joonazan** [comment]
#2118

**Comment by joonazan** [comment]
While writing this, I noticed that the camera module is pretty broken: the only difference between Perspective and Orthographic is that they have slightly different setters. However, those setters shouldn't be used because they do not update the inverse matrix.

I think there should be just convenience functions for creating a perspective/ortho matrix and nothing else. If someone wants to customize, he'll probably build a matrix from scratch anyway instead of using those setters.

I'll work on that some time next week.

**Comment by ishitatsuyuki** [comment]
Just FYI, the cached inverse matrix was primarily supposed to be used for culling. But for those cases the cache doesn't have to be inside the camera component itself I guess.

**Comment by joonazan** [comment]
@ishitatsuyuki Good to know. I think keeping the inverse matrix around is good, as it is also needed for screen to world computations and the invertibility check happens early, which is good.

My previous comment was worded like I wanted to remove inverse but I didn't mean that.

**Comment by chemicstry** [comment]
I believe this was fixed by #2118. If not, please reopen the issue.
