### ISSUE TITLE
Splitting book out of main repo

### ISSUE THREAD

**Issue by Defman** [amethyst/amethyst#1937]
**Problem**: Currently the amethyst book is embedded within the same repo containing the core code. This results in pull request and issues are mixed, and have to fork the entire repo to contribute to the book.

Further more, I believe it might scare some potential contributors away from contributing to the book, due to the fact they have to navigate the entire repo and submit a pull request next to the renderer rework.

**Comment by Frizi** [comment]
I agree with the reasoning, but also have some counterpoints that we have to address when moving book away from source.

Currenty when modifying some engine feature, the book is usually updated as part of usual find-replace workflow (it pops up when you search for things). The book is also tested against current local version of amethyst. It can do that only because the code is synchronized by being in the same repository. If we would split that off, we would have to choose a specific revision to test against. That means transitions to new versions no longer happen in lockstep and are ultimately a much bigger task.

**Comment by Defman** [comment]
**Problem:** Having the book tested against amethyst.
**Solution:** Setup a CI to run all code snippets from the book on a web hook. Then have some *bot* comment on all pull requests, to inform the contributor if any said snippets from the book fails.

**Problem:** Search and replace, workflow.
**Solution:** Have the CI also check all `use` statements from snippets.

The bot should also be able to create issues on the book, about broken snippets, and reference the commit/pull request.

**Comment by distransient** [comment]
Here is a problem, given a breaking change on the amethyst repo, the book must be updated to reflect the breaking changes. However, this introduces a CI catch-22. In order for CI on the book PR to pass, the Amethyst PR must be merged, while in order for the CI on the Amethyst PR to pass, the book PR must be merged. How do you solve this without entirely eschewing CI on the book repository?

**Comment by Defman** [comment]
There are a few ways to fix it, but they all have their pros and cons.

**First solution:** Have it so that any changes to amethyst main repo cannot be merged without a pull request that fixes all the issues in the book. Then have both pull request merge together/simultaneously in both repos.

**Second solution:** Make it so the book just create issues on the book repo for every broken snippet and then have it reference the breaking pull request.

I would prefer the second solution, since it is easier to implement and also separates the book from main development.
