### ISSUE TITLE
[BUG] amethyst_ui not on docs.rs

### ISSUE THREAD

**Issue by fkarg** [amethyst/amethyst#1941]
## Description

On [docs.rs](https://docs.rs), where amethys_ui should be, there is an error message. But see for yourself: [https://docs.rs/crate/amethyst_ui/0.7.0](https://docs.rs/crate/amethyst_ui/0.7.0)

## Reproduction Steps

1. Go to [https://docs.rs/crate/amethyst_ui/0.7.0](https://docs.rs/crate/amethyst_ui/0.7.0)
2. Done

## How to fix

The error message appears to come from trying to compile amethyst-rendy with no backend. Maybe execute with `--features emtpy`. Not sure how [docs.rs](https://docs.rs) works.

**Comment by distransient** [comment]
I believe this is a WONT-FIX because given [the incoming docs.rs changes](https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html) our crates may not even be capable of building on docs.rs in the first place (even despite adding [`package.metadata.docs.rs` flags to our manifest]([package.metadata.docs.rs])), and the documentation hosted on [docs.amethyst.rs](https://docs.amethyst.rs/) should be used instead anyways. We discussed just today on Discord ([link](https://discordapp.com/channels/425678876929163284/520296575751421973/625800758763323413)) the prospect of seeking a redirect feature for crates on docs.rs. This would likely be the best way forward.

**Comment by fkarg** [comment]
Probably a good idea. Showing the error message doesn't really look that good though, is a forward possible instead?

**Comment by distransient** [comment]
That's what we discussed in the Discord link
