### ISSUE TITLE
[FEATURE MODIFICATION] Add wrapper around colors

### ISSUE THREAD

**Issue by Luro02** [amethyst/amethyst#2022]
# Tasks
- add (not a lot!) of documentation on how to use the palette crate
- use the palette crate in examples instead of simple tuples

## Feature
All color attributes of widgets.

## Change
A wrapper, that makes it easier to work with colors.
I could imagine something like this
```rust
struct Color([f32, f32, f32, f32]);

impl Color {
    pub fn from_rgb(red: u8, green: u8, blue: u8) -> Self {
        /// conversion...
    }
}
```

## Reason
A color array in the form of `[f32, f32, f32, f32]` is very hard to use especially, because most colors are specified as `(red, green, blue)` tuples. A wrapper type would be quite convenient. This type can also be used to prevent the construction of invalid colors like `[255.0, 255.0, 255.0, 255.0]`. (the color array should be in a range of `0.0` to `1.0`?)

## Impact
This change breaks everything, where a public color field is?

## Additional Notes
I just started working with amethyst and still don't know how I can convert my rgb color to the color format, that amethyst requires? maybe document this? https://docs.amethyst.rs/stable/amethyst_ui/struct.UiTextData.html#structfield.color

**Comment by ishitatsuyuki** [comment]
Just a note, the color used for backgrounds (which in turn creates a 1x1 texture) is sRGB, and the color for text (which is just passed to shader) is linear RGB. You can check the source to verify which method is used to pass colors along.

(Also, just by the way I have been thinking of having a `Tint` component for all colorable ui components... instead of having a color field for each.)

**Comment by Luro02** [comment]
Nothing has changed, so it is still relevant
