### ISSUE TITLE
WASM: get parallel shred working without blocking main thread

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2191]
Currently [dispatch_par](https://github.com/amethyst/shred/blob/master/src/dispatch/dispatcher.rs#L87) in shred blocks the main thread while systems execute. Waiting in the main thread is not possible in wasm and causes a browser error.

The only way to synchronise with the main thread is to use `postMessage` in web workers so some kind of synchronisation helpers have to be implemented in https://github.com/amethyst/web_worker.

Whole call stack starting from `CoreApplication::handle_winit_event()` to shred's `dispatch_par()` has to be either made async or split into two parts. Unless there is some rust magic that would allow to save context and continue execution later?

**Comment by chemicstry** [comment]
After doing some more reading on multithreading wasm, I learnt that rust memory allocator had the same problem with not being able to lock the main thread. They solved it by having a dumb spin lock. Since allocation operation are quite fast, this lock is released quickly and does not impact browser responsiveness.

I think the same thing could be used for this case, because in theory dispatcher should finish executing all systems within one frame. If my reasoning is correct, spin locking for durations less than one frame should not have any impact on browser's responsiveness. The only downside is that while other threads are executing, the main thread will be loading CPU. The lock time really depends on how dispatcher groups systems and if they all have similar execution times there won't be any spin locking at all. In any case, this a better solution than single threaded execution.

Also, the async implementation through `postMessage` could be even worse, due to large overhead of this function. Although it is currently used to send work to workers, but I will try to implement dispatching through shared memory in `web_worker`.

**Comment by chemicstry** [comment]
Scratch that. Spin lock is not really possible because there are many ways that a deadlock could occur. For example `XmlHttpRequest` does not execute when main thread is blocked (main thread probably processes all io queues). I'm sure there are more cases, because this way of blocking main thread is out of spec and not recommended.

I will now try to make `advance_frame` async and see to how much extent everything needs to be modified.

**Comment by chemicstry** [comment]
So as we stand now, I don't see any reasonable way to make parallel dispatch work on wasm. These are the options I explored and their problems:
- Making `advance_frame` async. I don't see this happening without a major rewrite of the engine. Not only the whole call stack up to `dispatch_par` has to be rewritten in to async, but it also involves user code as dispatchers are exposed to the user. Also, currently engine is initialised on the stack (in main) and would have to be rewritten to heap initialisation to support exiting out of `main`.
- Running in a web worker. Tested, works, but has many problems. In order to initialise rendering in web worker `OffscreenCanvas` is used. Currently only chrome supports `HTMLCanvasElement.transferControlToOffscreen()` which allows DOM canvas to be linked to the offscreen canvas and draw directly. `winit` cannot access fullscreen, resize API with `OffscreenCanvas`. And one of the biggest breakers, there is no audio API in web worker, so all audio would have to be piped over `postMessage` which is very slow. Also, `requestAnimationFrame` has some hiccups in web worker and rendering is inconsistent, not sure what the problem is.

I would say we will have to deal with single-threaded dispatch for now unless someone dares to rewrite everything to async or web worker API improves over time.

**Comment by azriel91** [comment]
Firstly have to thank you for tracing through all those paths -- know it takes a lot of perseverance to work through so many barriers. For the parallel options:

* Making `advance_frame` async.

    I think it's not worth chasing this route -- there are many other issues in the list of libraries (`shred`, `shrev`, `specs`, `amethyst`) that can be improved with an `async` rewrite, and starting from a clean slate would be much cleaner than retrofitting `async` incrementally.

* Running in a web worker.

    Between this and single threaded dispatch, am guessing it's easier to maintain / work with the single threaded dispatch, and going through `postMessage` means the web worker version isn't going to provide more performance through parallelism as everything slows through the posting?

> I would say we will have to deal with single-threaded dispatch for now unless someone dares to rewrite everything to async or web worker API improves over time.

Agree with that; I may one day dare to rewrite everything, but not sure when that day is :v:

**Comment by azriel91** [comment]
Currently `shrev`'s dispatcher cannot be run with `dispatch_par` correctly if there is any system that sends an XmlHttpRequest (XHR). This is because the actual request is sent by the browser, which happens after the main thread returns from handling the winit event.

## Current State

This is what we currently have if we send an XHR directly in a system (single threaded dispatch -- `dispatcher.dispatch(world)`):

1. Main thread calls dispatcher.
2. A system in the dispatcher sends an XHR **synchronously**
3. The main thread waits for the request to finish, grabs the result, and continues.

:warning: While this executes the logic, the browser issues a deprecation warning as it makes the main thread unresponsive while the request happens. 

This is what would happen if we simply switch to multi-threaded dispatch -- `dispatcher.dispatch_par(world)`:

1. Main thread calls dispatcher, which runs in multiple `Worker` threads.
2. Worker thread: A system in the dispatcher sends an XHR **synchronously**.
3. Nothing actually happens, because:

    - the main thread is waiting for the worker thread to return (`dispatcher.dispatch_par()`)
    - the worker thread is is waiting for XHR to send, but it doesn't because main thread is waiting for worker thread to return.

What we do have functioning asynchronously (**not** Rust `async`) is loading assets:

1. `AssetStorage::process` runs using threads from the `Worker` pool. Those send XHRs synchronously, but are separate from the main thread's dispatch, which is why assets loaded from the `HttpSource` are actually running in parallel to the main thread.
2. When the main thread runs the dispatcher, querying an `AssetStorage` with the asset handle returns immediately (`None` or `Some`), so it doesn't cause unresponsive behaviour.

## Explore

We can try something similar to this:

1. In `app.rs`, hold onto a copy of `Arc<Mutex<ThreadPool>>`
2. In `handle_winit_event`, if event is `Event::MainEventsCleared`, then run the dispatcher's non-thread-local systems with the thread pool:

    ```rust
    thread_pool.spawn(|| {
        // dispatcher.dispatch_par(..)
        // but not including `dispatcher.dispatch_thread_local`
        // and we cannot send the dispatcher across -- only the stages
    });
    ```

    But since `Dispatcher` itself is `!Send` (since it holds the thread local systems), it must be called in such a way:

    ```rust
    dispatcher.dispatch_par_async();

    // which internally does:
    thread_pool.spawn(|| {
        for stage in stages {
            stage.execute(world);
        }
    });
    ```

3. Now, since we need to tell the main thread to wait for the dispatcher, but `ThreadPool::spawn` does not return any handle, we can send in an [`EventLoopProxy`](https://docs.rs/winit/0.22.1/winit/event_loop/struct.EventLoopProxy.html) which is `Send` (but `!Sync`):

    ```rust
    // maybe just before `event_loop.run(|| { .. })` in `run_winit_loop`
    let event_loop_proxy = event_loop.create_proxy();

    dispatcher.dispatch_par_async();

    // which internally does:
    thread_pool.spawn(|| {
        for stage in stages {
            stage.execute(world);
        }
        event_loop_proxy.send_event(ApplicationEvent::DispatchDone);
    });
    ```

4. Then back in `handle_winit_event`, when we match on event, and it is `UserEvent(ApplicationEvent::DispatchDone)`, we know that we can dispatch the thread local stuff.

    ```rust
   dispatcher.dispatch_thread_local();
    ```

Hmm, that might just work though it is a bit messy -- may need to tell `shrev` to accept sending that event as a closure; it's better than getting `shrev` to depend on `winit` (even if feature gated).

**Comment by chemicstry** [comment]
Looks like a candidate solution! Although, I wanted to point out a few minor issues. 

`MainEventsCleared` is fired by `requestAnimationFrame`, so rendering would happen outside its call. If web workers started to lag behind FPS limit, the animation frames would still be requested at the same interval and new `MainEventsCleared` could fire before previous dispatch is finished. What we have now is that `requestAnimationFrame` is called by winit after executing all events, so if `MainEventsCleared` takes long time, FPS is nicely throttled.

And thinking further, what to do with user dispatchers that are called inside state? Some simple mechanism should be provided so you wouldn't have to deal with events.

**Comment by azriel91** [comment]
ah, we have to remember some `DispatchStatus` or something inside `CoreApplication`, and choose to either do nothing, dispatch, or wait for dispatcher when the winit event comes in.

Oh ya, hadn't thought of user dispatchers. Naive / immediate solution may be to get the user to:

* pass in some logic that determines whether the application has finished waiting for an event loop
* when a winit user event comes in, give that to the user logic, and it returns "yay continue", or "no wait for another dispatcher end event"

Would be nice to not to have to think of that :stuck_out_tongue:. I'd defer it from this issue though, since this would be partway there, and there's probably a better way to do the state dispatchers.

**Comment by azriel91** [comment]
Also, there's proof that XHRs are not sent until control is returned from the main thread to the browser:

https://github.com/azriel91/worker_sync_xhr

**Comment by azriel91** [comment]
We don't have a good place to split the dispatcher execution / resume advancing frame -- the dispatcher is run in `State::update`, which can be user code (and who knows what else they run after that).

So if we send an application event at the end of the dispatcher execution, we need to break API for users to go "first half of `State::update` until you run the dispatcher", and "second half of `State::update` until you return the transition".

I don't think it's worth creating that kind of API for WASM multithreading, would have to design something better.
