### ISSUE TITLE
WASM: fix GL rendering

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2192]
Currently pong in wasm looks like this:

![pong](https://i.imgur.com/HuYkC59.png)

Ball sprite is glitchy, paddles only appear on the first frame.
Needs investigation.

**Comment by azriel91** [comment]
On branch [`feature/2192/fix-gl-rendering`](https://github.com/amethyst/amethyst/tree/feature/2192/fix-gl-rendering):

* While running pong, these log messages appear:

    ```
    [WARN][gfx_backend_gl] [API/Performance] ID 14 : Incompatible sampling format (ISL_FORMAT_R8G8B8A8_UNORM_SRGB) for rbc (MESA_FORMAT_R8G8B8A8_SRGB)
    ```

* These [come from the mesa open GL driver](https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/src/mesa/drivers/dri/i965/intel_mipmap_tree.c#L1956).
* The mapping [appears to be intentional](https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/src/mesa/drivers/dri/i965/brw_surface_formats.c#L68) -- note this is the same repository.

**Comment by azriel91** [comment]
When running the `ui` example with `"gl"`, `gfx` panics in `src/backend/gl/src/device.rs:1306`:

```rust
let desc = conv::describe_format(format).unwrap();
```

This is because `describe_format` returns `None` when `format` is `Rgb8Srgb`:

```
[/mnt/data/work/github/gfx-rs/gfx/src/backend/gl/src/device.rs:1306] format = Rgb8Srgb
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /mnt/data/work/github/gfx-rs/gfx/src/backend/gl/src/device.rs:1306:20
```

Rendy uses this in `texture/src/format/palette.rs`: 

```rust
define_load! {
    pub fn load_from_srgb<T: Component>(Srgb) -> Rgb8Srgb NO;
    // ..
}
```

**Comment by chemicstry** [comment]
I'm not sure if it's because I'm running windows, but `amethyst_ui` also crashes due to incorrect `Swizzle` for gl. I didn't dig deep, but it seems that vulkan accepts any swizzle and does the transformation inside the driver. GL doesn't support that and expects swizzle to always be RGBA.
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Swizzle(Zero, Zero, Zero, R)`,
 right: `Swizzle(R, G, B, A)`', C:\Users\User\.cargo\git\checkouts\gfx-5aa16ebf28522941\3e6db5f\src\backend\gl\src\device.rs:1469:9
stack backtrace:
   0: core::fmt::write
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libcore\fmt\mod.rs:1069
   1: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\io\mod.rs:1427
   2: std::sys_common::backtrace::_print
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\sys_common\backtrace.rs:62
   3: std::sys_common::backtrace::print
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\sys_common\backtrace.rs:49
   4: std::panicking::default_hook::{{closure}}
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:198
   5: std::panicking::default_hook
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:218
   6: std::panicking::rust_panic_with_hook
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:511
   7: std::panicking::begin_panic_handler
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:419
   8: std::panicking::begin_panic_fmt
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:373
   9: gfx_backend_gl::device::{{impl}}::create_image_view
             at C:\Users\User\.cargo\git\checkouts\gfx-5aa16ebf28522941\3e6db5f\src\backend\gl\src\device.rs:1469
  10: rendy_resource::image::ImageView<gfx_backend_gl::Backend>::create<gfx_backend_gl::Backend>
             at D:\Dev\amethyst_wasm\rendy\resource\src\image.rs:242
  11: rendy_factory::factory::Factory<gfx_backend_gl::Backend>::create_relevant_image_view<gfx_backend_gl::Backend>
             at D:\Dev\amethyst_wasm\rendy\factory\src\factory.rs:353
  12: rendy_factory::factory::Factory<gfx_backend_gl::Backend>::create_image_view<gfx_backend_gl::Backend>
             at D:\Dev\amethyst_wasm\rendy\factory\src\factory.rs:380
  13: rendy_texture::texture::TextureBuilder::build<gfx_backend_gl::Backend>
             at D:\Dev\amethyst_wasm\rendy\texture\src\texture.rs:464
  14: amethyst_ui::glyphs::create_glyph_texture<gfx_backend_gl::Backend>
             at .\amethyst_ui\src\glyphs.rs:635
  15: amethyst_ui::glyphs::{{impl}}::run::{{closure}}<gfx_backend_gl::Backend>
             at .\amethyst_ui\src\glyphs.rs:163
  16: palette::alpha::Alpha<palette::rgb::rgb::Rgb<palette::encoding::linear::Linear<palette::encoding::srgb::Srgb>, f64>, f64>::new<palette::encoding::linear::Linear<palette::encoding::srgb::Srgb>,f64,f64>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\palette-0.4.1\src\rgb\rgb.rs:178
  17: amethyst_ui::glyphs::{{impl}}::run<gfx_backend_gl::Backend>
             at .\amethyst_ui\src\glyphs.rs:161
  18: shred::system::{{impl}}::run_now<amethyst_ui::glyphs::UiGlyphsSystem<gfx_backend_gl::Backend>>
             at C:\Users\User\.cargo\git\checkouts\shred-a3307cb74879c8e8\bfa6b83\src\system.rs:140
  19: shred::dispatch::dispatcher::Dispatcher::dispatch_thread_local
             at C:\Users\User\.cargo\git\checkouts\shred-a3307cb74879c8e8\bfa6b83\src\dispatch\dispatcher.rs:115
  20: amethyst::game_data::GameData::update
             at .\src\game_data.rs:47
  21: amethyst::state::StateMachine<amethyst::game_data::GameData, amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>>::update<amethyst::game_data::GameData,amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>>
             at .\src\state.rs:447
  22: amethyst::state::StateMachine<amethyst::game_data::GameData, amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>>::update<amethyst::game_data::GameData,amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>>
             at .\src\state.rs:447
  23: amethyst::app::CoreApplication<amethyst::game_data::GameData, amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>, amethyst::state_event::StateEventReader<amethyst_input::bindings::StringBindings>>::advance_frame<amethyst::game_dat
             at .\src\app.rs:488
  24: amethyst::app::CoreApplication<amethyst::game_data::GameData, amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>, amethyst::state_event::StateEventReader<amethyst_input::bindings::StringBindings>>::handle_winit_event<amethyst::gam
             at .\src\app.rs:344
  25: amethyst::app::{{impl}}::run_winit_loop::{{closure}}<amethyst::game_data::GameData,amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>,amethyst::state_event::StateEventReader<amethyst_input::bindings::StringBindings>>
```

**Comment by azriel91** [comment]
Oh yes I went past that by adding a `"gl"` feature to `amethyst_ui`. I'm now at "the application runs, but it's just a black screen and no errors", so now it's educated guessing / renderdoc and hoping to find something.

**Comment by azriel91** [comment]
What it should look like:

![sprites_ordered_vulkan](https://user-images.githubusercontent.com/2993230/77618333-01db8880-6f9b-11ea-959a-8598d60ceb44.png)

What it actually looks like:

![gl_pixel](https://user-images.githubusercontent.com/2993230/77618378-1455c200-6f9b-11ea-98c0-a891c3cb977a.png)

Using [Renderdoc](https://renderdoc.org/), the texture and vertices appear to be in the correct places.

This is because [`Surface.swapchain` ](https://github.com/amethyst/gfx/blob/wasm/src/backend/gl/src/window/glutin.rs#L95) is `None`. When manually setting `frame_buffer_width` and `frame_buffer_height` in [`TargetPlan::metadata`](https://github.com/amethyst/amethyst/blob/1d491d18310edb1432a51e602603e202496c2324/amethyst_rendy/src/bundle.rs#L646-L647), it renders correctly.

[Configuring it should set the size](https://github.com/amethyst/gfx/blob/wasm/src/backend/gl/src/window/glutin.rs#L141-L146), but it is rather difficult:

1. [`configure_swapchain`](https://github.com/amethyst/gfx/blob/wasm/src/backend/gl/src/window/glutin.rs#L122) needs a `&Device` and `SwapchainConfig`.
2. `&Device` can be obtained from [`PhysicalDevice::open`](https://github.com/amethyst/gfx/blob/wasm/src/backend/gl/src/lib.rs#L575).
3. Example of calling that method is in the [gfx `quad` example](https://github.com/amethyst/gfx/blob/wasm/examples/quad/main.rs#L258-L273).

Closest attempt is to put the following (non-compilable) snippet of code [here](https://github.com/amethyst/amethyst/blob/1d491d18310edb1432a51e602603e202496c2324/amethyst_rendy/src/bundle.rs#L617): 

```rust
use hal::{
    adapter::PhysicalDevice,
    queue::family::QueueFamily,
    window::{Extent2D, PresentationSurface, Surface},
    Instance,
};

// This line doesn't compile, haven't checked why Rust doesn't see the trait impl.
let adapter = Instance::enumerate_adapters(surface.raw()).remove(0);
// Build a new device and associated command queues
let family = adapter
    .queue_families
    .iter()
    .find(|family| {
        surface.raw().supports_queue_family(family)
            && family.queue_type().supports_graphics()
    })
    .unwrap();
let mut gpu = physical_device
    .open(&[(family, &[1.0])], hal::Features::empty())
    .unwrap();
let device = &gpu.device;
let capabilities = surface.capabilities(physical_device);
let extent_2d = Extent2D {
    width: 400,
    height: 75,
};
let swapchain_config = hal::window::SwapchainConfig::from_caps(
    &capabilities,
    surface.format(&physical_device),
    extent_2d,
);
surface.raw().configure_swapchain(device, swapchain_config);
```

**Comment by chemicstry** [comment]
A blind guess, but in one of the OpenGL attempts, `Extent2D` is added to the surface https://github.com/amethyst/amethyst/pull/1877/files#diff-b1132ba9c55a0380c1a9d246a7940c90L635. Maybe related?

**Comment by azriel91** [comment]
Yeap that was it :v:. Have gotten `sprites_ordered` working with the method #1877 used, but `gltf` and `ui` examples don't work -- `gltf` needs [`blit_image` which is `unimplemented()!`](https://github.com/amethyst/gfx/blob/wasm/src/backend/gl/src/command.rs#L797), and `ui` needs the `Rgb8Srgb` format ([earlier comment with details](https://github.com/amethyst/amethyst/issues/2192#issuecomment-603656444)).

For future reference, `configure_swapchain` doesn't actually set the `extent` that is read in `amethyst_rendy`, the [extent just returns `None`](https://github.com/amethyst/gfx/blob/wasm/src/backend/gl/src/window/glutin.rs#L200).

Gonna PR and open separate issues for the other two examples -- `gfx-rs/gfx` is switching backend implementation for GL from `glutin` to `surfman` for non-windows OSes ([PR](https://github.com/gfx-rs/gfx/pull/3151), [wider issue](https://github.com/gfx-rs/wgpu/issues/450)).

**Comment by azriel91** [comment]
https://github.com/amethyst/amethyst/pull/2198 gets GL rendering, though it's upside down. I haven't figured out the right way of flipping it `@ishitatsuyuki` mentioned that it's better to flip it in lower layers instead of the camera (spirv converter), but I haven't managed to do that correctly.

Note that the `amethyst/gfx:wasm` and `amethyst/rendy:wasm` forks are both updated, and the `amethyst/amethyst:wasm` branch is updated when #2198 is merged.

**Comment by azriel91** [comment]
I reverted the update to `gfx-hal` 0.5 -- couldn't figure out how to get the upside down coordinates flipped correctly (0.5 hal update for `amethyst/gfx` fork are in the [`wasm-hal-0-5`](https://github.com/amethyst/gfx/tree/wasm-hal-0-5) branch, all others are reverted commits).

**Comment by azriel91** [comment]
Turns out the difference is due to the window height being small. Increasing the window height results in the same output.

GL/Vulkan:

![sprites_ordered_gl_height_increased](https://user-images.githubusercontent.com/2993230/77978073-a70cad00-735d-11ea-9bd6-7c4b386eb86f.png)

The forks/branches have been re-updated to `gfx-hal 0.5`, and the inverted rendering corrected in [`5d10084`](https://github.com/amethyst/rendy/commit/26ec46deeda4ab0368e3c0d30577c4a5ef821683).

---

Next task is to get transparency working correctly:

GL:

![pong_gl](https://user-images.githubusercontent.com/2993230/77977705-e4bd0600-735c-11ea-9222-3cea55f11a5b.png)

Vulkan:

![pong_vulkan](https://user-images.githubusercontent.com/2993230/77977707-e5ee3300-735c-11ea-97a2-df76041e34b3.png)

---

Parking this to pick up https://github.com/amethyst/amethyst/issues/2202.

**Comment by chemicstry** [comment]
Most of the rendering artifacts were due to the depth buffer not being cleared. Fixed in https://github.com/amethyst/gfx/commit/35c45acb43eebf989d06ba34141e43738d77b991

**Comment by azriel91** [comment]
Random gold nugget from the gamedev chat:

> contexts (GL) and instances (VK) etc are each connected to a single window, and with GL they're also a thread local
>
> Lokathor

**Comment by chemicstry** [comment]
I believe this can be closed. There are still issues with some of the examples (such as missing pixel format, etc), but these can now be resolved as separate issues.
