### ISSUE TITLE
Composable Shaders with a similar architecture to ClojureScript's Gamma

### ISSUE THREAD

**Issue by codri** [amethyst/amethyst#22]
Hi,

I've stumbled upon this interesting project(Gamma at https://github.com/kovasb/gamma) that uses datasctructures to represent and compose Shaders, and functions to compose/compile them. There's a StrangeLoop presentation that explains the premise better.

I wonder if amethyst can benefit from a simple graphics model on top of OpenGL.

Thanks

**Comment by ebkalderon** [comment]
@codri Seems really neat! I'll have to play around with this framework a bit before I comment on it, though. Thanks for the find.

**Comment by ebkalderon** [comment]
@codri So far, I'm loving the ideas behind Gamma. Being able to compose shaders like this is rather nice, plus it could potentially be used as a layer of abstraction over GLSL, HLSL, etc. which is huge. 

However, I do believe such a layer would probably be better utilized in the [Amethyst toolchain](https://github.com/ebkalderon/amethyst_tools) rather than in the runtime engine. Perhaps when `amethyst build` is called, it calls another hypothetical utility which translates shader code written in some flexible language like Scheme into one of the target platform's supported shading languages (e.g. SPIR-V/HLSL for Windows, SPIR-V/GLSL for Linux, and GLSL for other possibly older platforms).

Keep in mind, I'm just brainstorming ideas. It is too early to start building, but at least it provides some food for thought.

**Comment by Xaeroxe** [comment]
cc @omni-viral Does this issue look useful to you?

**Comment by omni-viral** [comment]
@Xaeroxe you can set it low priority improvement at leave open. We will need to improve our tools

**Comment by minecrawler** [comment]
I think, something like that is extremely useful, because it allows us to separate different implementations for certain effects. For example, I might decide to use lighting, however I might want to use a lighting/shadow variant which Amethyst does not support (e.g. [Voxel Cone Tracing Illumination](https://github.com/Friduric/voxel-cone-tracing)), so I could implement it and just replace the standard lighting/shadow shader like that - ideally sending the whole new module upstream to store like a library ;)

However, I think that shader modules should be selectable during runtime, too, because I might want to use better visual effects on a stronger computer, but reduce that to basic ones on weaker machines. Maybe it is possible to do so by using different entry points?

**Comment by Rhuagh** [comment]
This should be doable after hal, using spir-v shader modules

**Comment by torkleyy** [comment]
I think we can close this issue, it doesn't provide any valuable information and we'll get this for free soon.
