### ISSUE TITLE
WASM: find a way to provide existing canvas

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2202]
Currently canvas is automatically created by winit and appended to the `<body>`. Most users will probably want to provide their own canvas element that is within complex DOM structure. Could it be provided via `DisplayConfig`? This field would not be serializable, but we already have `Icon` with is not serializable either.

**Comment by azriel91** [comment]
I think it's possible to do this:

* Allow the user to define a canvas element in HTML
* Pass that as a `web_sys::HtmlCanvasElement` into pong's startup `run()` function
* Copy the attributes from the user's canvas element onto the `Canvas` provided by `winit::Window`
* Replace the user's canvas element with winit's `Window` canvas

For the third point, it's clashing with the functionality from `DisplayConfig`. Perhaps we don't have to do that, and just take the user's canvas element as the hint for where the put the winit canvas.

**Comment by minecrawler** [comment]
I don't think replacing the user's canvas element is a good idea, because the user might have wired the element up with event handling already, which is destroyed by replacing it. Imho, Amethyst should use a provided canvas element instead of creating its own. The question is how and where to pass it into Amethyst, and how Amethyst can merge its own canvas settings into the user provided one (viewport width & height, gl context, etc. come to mind).

This could be discussed in a bigger scope, because rendering Amethyst into an existing UI is not web-specific. For example how does Amethyst handle user-created windows and element-handlers in general? What if I want to add Amethyst into an existing native application, but only render Amethyst to a certain handler within the application?

**Comment by chemicstry** [comment]
Winit has `with_canvas` option in web window builder extensions so there's no need to replace

**Comment by azriel91** [comment]
Got this working in `pong_wasm`, and have pushed the changes to `master`.

It still panics when running though ([`device.rs`](https://github.com/amethyst/gfx/blob/wasm/src/backend/gl/src/device.rs#L823)):

```rust
panicked at 'called `Option::unwrap()` on a `None` value', /mnt/data/work/github/gfx-rs/gfx/src/backend/gl/src/device.rs:823:41
```

**Comment by azriel91** [comment]
Push that to https://github.com/amethyst/amethyst/issues/2205.
