### ISSUE TITLE
WASM: Load input bindings from server

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2214]
Currently initializing input `Bindings` using `input_bundle.with_bindings_from_file` [reads from the file system](https://github.com/amethyst/amethyst/blob/efd1e1c/amethyst_config/src/lib.rs#L126). For WASM support, it should load this from the server instead.

See [`HttpSource`](https://github.com/amethyst/amethyst/blob/74fd3e2/amethyst_assets/src/source/http.rs#L57) for how this is done for assets.

**Comment by chemicstry** [comment]
The synchronous `XmlHttpRequest` can't be used in the main thread so config has to be either supplied from javascript side or we need async loading. Since both solutions would reside in user code I think supplying it from the javascript would be easier. Since we already provide canvas, maybe we could have a builder like interface from javascript side? Like:
```
game
    .with_canvas(canvas)
    .with_bindings(await fetch('config/bindings.ron'))
    .run()
```
