### ISSUE TITLE
WASM: Rendering on FireFox does not work

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2230]
FireFox (nightly) fails with `WebGL warning: drawArraysInstanced: One active vertex attrib (if any are active) must have a divisor of 0.`

Issue is discussed here https://github.com/KhronosGroup/WebGL/issues/2419

TLDR: This is caused by all vertex shader attributes being instance rate (at least in UI and sprite passes). This was a limitation in initial WebGL spec, because of D3D9 backend. This is now lifted and works in chrome, but firefox seems to still use the old spec.

There is a workaround to add dummy vertex rate attribute as implemented in https://github.com/amethyst/amethyst/pull/1877, but I think it's better to just wait until firefox releases an update and use chrome in the meantime.

**Comment by azriel91** [comment]
Needs the following options enabled:

* [`javascript.options.shared_memory`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer).
* `dom.postMessage.sharedArrayBuffer.withCOOP_COEP`
* `dom.postMessage.sharedArrayBuffer.bypassCOOP_COEP.insecure.enabled` (can only be enabled on nightly / dev builds).

Set these in `about:config`.

Otherwise it fails to create workerpool.

```
Failed to create WorkerPool: JsValue(TypeError: The WebAssembly.Memory object cannot be serialized. The Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy HTTP headers will enable this in the future.
```

**Comment by leo60228** [comment]
Should this not be reported to Firefox?
