### ISSUE TITLE
Reorganize code and cyclic dependencies

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2277]
Legion port revealed a lot of flaws in current code organisation. We have features to disable different crates, but a lot of them don't work because everything is interconnected with many cyclic dependencies.

`amethyst_utils` - this should have bare basic functions without any dependencies (external only). But instead it depends on window, rendy, assets, controls, derive. Since it's a core dependency of `amethyst` none of these can be excluded from the build.

`amethyst_derive` - this is just not how you group things. Why would you move derive macros into a separate crate instead of keeping it next to what it derives?

I'm sure there are more. Will update when I encounter.

**Comment by jojolepro** [comment]
> amethyst_utils - this should have bare basic functions without any dependencies (external only). But instead it depends on window, rendy, assets, controls, derive. Since it's a core dependency of amethyst none of these can be excluded from the build.

what you are describing is amethyst_core. amethyst_util was designed to make multiple other crates work together, and make the engine easier to use.

**Comment by khionu** [comment]
Proc macros must be in a separate crate. That said, they don't need to import code that's relevant to what they generate, though it does make it easier. This is a known inconvenience in Rust.

**Comment by ezpuzz** [comment]
most of amethyst_derive has been removed.  I've made utils optional but default because they are used in every example. 

simplifying the crate structure is an ongoing effort and using cargo-deny along with other tools should help us to keep it maintainable and work well with external tooling.

closing this issue as the concerns have been mostly addressed, I will open a separate issue for breaking utils apart to allow for smaller builds when possible.
