### ISSUE TITLE
[MAINTENANCE] PR Checklist vs Contributing Checklist

### ISSUE THREAD

**Issue by MrTanoshii** [amethyst/amethyst#2359]
## Description

Is there a particular reason why [Pull Request Template](https://github.com/amethyst/amethyst/blob/master/.github/pull_request_template.md) does not have `mdbook test book -L target/debug/deps` as quoted from [Contributing](https://github.com/amethyst/amethyst/blob/master/docs/CONTRIBUTING.md)

## Reason

Jenkins is, at the moment this Issue is written, failing because of the `mdbook test` which is not checked at all by the contributor.

## Impact

The test is an unnecessary extra step for contributors who did not modify the book.

## Additional Information

Jenkins runs
`mdbook test -L ./target/debug/deps book`
while [Contributing](https://github.com/amethyst/amethyst/blob/master/docs/CONTRIBUTING.md) recommends
`mdbook test book -L target/debug/deps`

**Comment by CleanCut** [comment]
The To-Do's that I see in this issue are:
- [ ] Move the `mdbook`-running information from the "Pull Requests" section to the "Writing Documentation" section (it's extremely useful to run the command yourself and get quick feedback rather than waiting for CI).  Also, once CI works, one of the checks should alert you if your examples don't compile.
- [ ] Compare the "Pull Request" section to the template and make sure the rest of the information correlates.

@MrTanoshii Would you like to take a first pass at doing the update? I'd be happy to be the reviewer!

Related:
- Fixing the book is in progress in https://github.com/amethyst/amethyst/issues/2365
- Migrating to a CI that works with forks is in progress in https://github.com/amethyst/amethyst/pull/2364

**Comment by MrTanoshii** [comment]
Added to my PR #2368
