### ISSUE TITLE
Quick example is outdated, there is no --template switch in cargo

### ISSUE THREAD

**Issue by ArmsOfSorrow** [amethyst/amethyst#237]
I wanted to build a quick sample, but the guide is outdated.
First I thought it was a stable/nightly or a Windows issue, but the behavior on Linux is the same, regardless of version.
Tested versions are 1.17 (stable) and 1.19.0-nightly (557967766 2017-05-26).

**Comment by torkleyy** [comment]
This is a known issue; also see https://github.com/amethyst/tools/issues/37

This will be fixed once we got all kind of rewrites finished, but for now we're pretty busy with them. I'd recommend looking at the [examples in the `0.4` branch](https://github.com/amethyst/amethyst/tree/release-0.4/examples) for now.

**Comment by nchashch** [comment]
Did #215 fix it?

**Comment by ArmsOfSorrow** [comment]
Yes, after adjusting the path to the config.yml it does open an empty window.

**Comment by ebkalderon** [comment]
Apparently the Cargo team [removed the `--template` switch](https://github.com/rust-lang/cargo/pull/3878) back in March due to recent feedback and second thoughts. I'm sorry for not noticing this earlier!

Given that this issue hasn't yet been fixed (both docs and amethyst/tools are out of date), I'm reopening this issue until we resolve this. This will not block the 0.4.3 release.

**Comment by Xaeroxe** [comment]
The template switch isn't coming back, so this isn't so much stalled as it is "need another solution"

**Comment by ebkalderon** [comment]
@Xaeroxe Since you removed the `--template` reference from the README, perhaps we should close this issue.

@amethyst/tools-devs In the meantime, we should try to modernize `amethyst_tools` to get the desired functionality.
