### ISSUE TITLE
Implementing Audio

### ISSUE THREAD

**Issue by Aceeri** [amethyst/amethyst#243]
Audio is a large part of creating an interesting game even if it isn't noticed very much aside from music, so it should probably be somewhat high in the priority list. Right now we should probably use [cpal](https://github.com/tomaka/cpal) for Mono/Stereo audio, however, there are no surround/3d audio libraries available in Rust yet.

Should we create a 3d audio library in Rust or should we just use an existing library in another language ([OpenAL-soft](http://kcat.strangesoft.net/openal.html)) and just patch it in with dlls?

**Comment by diegor8** [comment]
Amethyst doesnt use sdl , right ?

**Comment by Aceeri** [comment]
I believe it uses glutin for windowing/input.

**Comment by nchashch** [comment]
Maybe we should also consider [alto](https://crates.io/crates/alto).

**Comment by Aceeri** [comment]
@nchashch Those are bindings for OpenAL-soft, still need the dlls for OpenAL though.

**Comment by torkleyy** [comment]
While having a pure-Rust library would be great long-term, `alto` would make it easier for us right now. In case we decide to build our own library, I'd be happy to create a repo and maintain it. Please note, however, I didn't do 3D audio programming before so I had to read me through this first.

**Comment by vitvakatu** [comment]
Also there is [rodio lib](https://github.com/tomaka/rodio). It's used by `ggez`.

**Comment by torkleyy** [comment]
@vitvakatu While it may be interesting when programming a 3D Audio library, it isn't one itself.

**Comment by vitvakatu** [comment]
@torkleyy yes, I know. We can use it for the first time before implementing 3d-audio, or, as you said, it can help us in case we'll write new library.

**Comment by nchashch** [comment]
Developer-hours are scarce so I am somewhat more inclined to use OpenAL, rather than roll our own 3d audio library or add 3d audio support to `rodio`, because then we would get a much higher functionality added/developer-hour ratio. I think carrying around dlls/.a files would be okay, if we automated it with project template, as @Aceeri suggested, so that users don't have to worry about it.

It would be cool to make amethyst's audio API backend agnostic, so that in the future if there is a pure rust library for 3d audio we could replace OpenAL with it, preferably without breaking the API.

So I think it would be best first to implement audio support using `alto`, make the API backend agnostic, and then if there is a pure rust 3d audio library replace `alto` with it, without breaking the API too much.

**Comment by minecrawler** [comment]
Just a quick note: I know that there is https://github.com/klingtnet/rsoundio , which already handles multiple backends (Linux: JACK, PulseAudio, ALSA; macOS: CoreAudio; Windows: WASAPI). It is a Rust wrapper for the libsoundio library, written in C, so it probably is not ideal/usable for Amethyst, however, it might be interesting to take ideas from its API.

**Comment by torkleyy** [comment]
@minecrawler Taking a quick look, it seems it doesn't provide any 3D audio, which is however the most importent criterion for us.

**Comment by Xaeroxe** [comment]
https://github.com/tomaka/rodio/pull/125 rodio PR to add 3D audio.

**Comment by Xaeroxe** [comment]
https://github.com/amethyst/amethyst/pull/265 PR to add audio to amethyst

**Comment by Xaeroxe** [comment]
PR closed, thus I am closing this issue!
