### ISSUE TITLE
Confusing/incomplete system initialization example in book

### ISSUE THREAD

**Issue by rhys-vdw** [amethyst/amethyst#2594]
## Description

https://github.com/amethyst/amethyst/blob/f0dd344953a8748daee02ea6ca8b568056edc997/book/src/concepts/system.md#L73-L83

This code points shows a system with a field that stores a reference to an Entity. Unfortunately it does now show how one might initialize this reference.

As far as I can tell this code actually _must_ be wrong because the field is not `pub` and is not referenced by the impl. 

## Reason

The book should show how to initialize this field, and show only examples that are usable.

I'm not the first person to be caught by this.

my question: https://discord.com/channels/425678876929163284/476032191567233025/793313125553930260
older example: https://discord.com/channels/425678876929163284/476032191567233025/754379398450511993

## Additional Information

I still have no idea how to store a reference to an entity in a system so I can't provide the fix!

**Comment by ezpuzz** [comment]
This is much easier with Legion on master fortunately.

Here is an example for 0.15.3 though:  https://github.com/radium-io/sanity/blob/main/sanity-bin/src/system/hud.rs

The book example makes no sense because you wouldn't know the Entity for player at the time you build the dispatcher in `main`.  It should almost always be `Option<Entity>` or `Vec<Entity>` on a system.

I guess in Legion you could modify the dispatcher later after entities exist, but not sure of the whole user story for that yet.

We will keep this in consideration when rewriting the book.
