### ISSUE TITLE
Update pong tutorial in the book to use `--package` instead of `--example`

### ISSUE THREAD

**Issue by kmdreko** [amethyst/amethyst#2640]
The Amethyst book still says to use `cargo run --example` for running the tutorials. See here: https://book.amethyst.rs/book/stable/pong-tutorial

This can cause confusion for newcomers. See here: https://stackoverflow.com/questions/66377857/rust-amethyst-pong-tutorial-examples-give-error-no-example-target-named-pong

It should be updated to use `-p` or `--package`.

**Comment by AlveLarsson** [comment]
Thanks for the heads up, will fix this!

**Comment by AlveLarsson** [comment]
Okay, so this is not an issue, it has been taken care of on the main branch
The docs are stable only (0.15.x) on the website, we may want to say instead of cloning directly from the main branch where things can constantly change we re-direct to a Github tag for that specific release the docs instance is referring to
