### ISSUE TITLE
Finalize input design

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#275]
I'd like us to specify the requirements of our input handler. The goal is to make the implementation / reviewing easier by specifying things first.

Now, we don't have to actually support all of the following things. But I would like to have a system which is designed for those, so that it is possible to implement them with no to minor breakage.

Here are some points that would be important for me:

* Three core concepts: `Action`, `Axis`, `Absolute`
* Have maps for each of the above concepts in `InputHandler` which map a `String` to the respective value (A combination of two `bool`s for `Action`, a float for `Axis` as for `Absolute`)
* Support many kinds of input sources: mouse (buttons, scroll wheel, movement, position), keyboard(s), gamepads, touch screens, virtual sources (so we can have touch UI elements for input on e.g. Android)

---

## Implementation notes

* Expose the above maps as `pub` fields, in order to make the API simple and obvious

**Comment by Xaeroxe** [comment]
So as for an implementation plan:

The existing Button enum was intentionally designed to be expandable so that as our backend becomes more robust we can just add different types to it.  So in order to support new input devices we mostly just need some way to receive the input in Rust, at which point it's relatively trivial to adapt the existing API to account for it.  It might be desirable to change the internal storage types to use buttons instead of the raw hardware values, just to help simplify the implementation and keep it easily expandable

Our current axis type only operates on buttons, it definitely should be expanded to operate on physical analog axes, I'm just not quite sure what the best approach to that is.  My first reaction is to maybe use a trait object and map to those, but I'm also wary of those because I know they can kill performance.  I think it might be OK in this instance because each axis is usually only polled once per frame.

Absolute would actually be relatively simple, just expose a HashMap<String, f32>.

**Comment by torkleyy** [comment]
Couldn't we just use an enum for axes?

**Comment by Xaeroxe** [comment]
That would work too.  I like that approach much better.

**Comment by Xaeroxe** [comment]
So to summarize:
We can add the absolute stuff right now at virtually no cost to us.
Add 
```Rust
pub enum Axis {
    Virtual{pos: Button, neg: Button},
    Manual(f32),
}
```

As for how to make other input devices work, step 1 is to get a raw stream of data from them into Rust, from there it's relatively trivial to get them interacting with the InputHandler.

**Comment by torkleyy** [comment]
I wouldn't call the one with buttons `Virtual` and this enum does mix value and binding. `f32` is a value and these buttons are the binding for one axis. We need e.g. device ids for other axes.

**Comment by Xaeroxe** [comment]
@torkleyy that sounds good, we just need a grasp on what those device ids are first.  The Manual axis is primarily for a kind of "screw it manage your own input" approach so the user (or a virtualized hardware device such as an Android touchscreen DPAD) can stick whatever value it wants in there.

**Comment by torkleyy** [comment]
I would actually rename what you called `Manual` to `Virtual`

**Comment by Xaeroxe** [comment]
:+1:

**Comment by OvermindDL1** [comment]
Why would there be buttons on a pos/neg axis?!

**Comment by Xaeroxe** [comment]
@OvermindDL1 it emulates a digital axis, such as W and S or A and D in WASD.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 it emulates a digital axis, such as W and S or A and D in WASD.

I'd definitely not have the input system know anything about that at all.  Like I've mentioned elsewhere, my filesystem path you could connect events together (like say an axis movement to a button press) while applying a filter to the event (only propagate if it exceeds some value, and if it does then alter it to be a boolean instead of a float).  Every time I tried to overcomplicate any system from input to more to handle more than what they really have the raw information for it ended up becoming unmanageable over long time.

**Comment by Xaeroxe** [comment]
It sounds like your idea is to not have an input system at all and just pass raw data.  I'm not terribly interested in that approach because it falls apart in a hurry the instant you're not working on a Unix system.  Having axes configured in this way prevents you from having to write code to handle both negative and positive cases.  You just code to handle a single axis value.

**Comment by OvermindDL1** [comment]
> It sounds like your idea is to not have an input system at all and just pass raw data. I'm not terribly interested in that approach because it falls apart in a hurry the instant you're not working on a Unix system. 

I never passed raw data, everything was wrapped up in an event structure.

Also nothing was unix specific at all, my code runs fine on linux and windows (never tested mac but the interfaces I used 'should' have worked fine).  I'm unsure why you mentioned Unix system at all actually (am I missing something?).

For example, a mouse being moved 'up' might send (in ML'y notation since significantly shorter than the C++:
```ocaml
{type: MouseMove, mouse: 0, axis: 0, relative: +867.0, scale: 0.8}
```
And that would be sent from my virtual node of `/dev/mouse/0/axis/0/on_change`, which you could wire up with a filter like (C++ syntax):
```cpp
context->forwardEvent("/dev/mouse/0/axis/0/on_change", "/player/0/action/forward", [](const EventMap &event){
  if(event.get("Relative"_atom64, 0) > 0) {
    return EventMap.create("Action"_atom64, "pressed"_atom64, true, "original_event"_atom64, event, etc...);
  } else {
    return EventMap.none();
  }
});
```
And that would send any mouse movement up to the player 0 action of 'forward' (which other things could then be bound on to run some code) while filtering the event as it passed through (either returning it unaltered, returning an altered copy, constructing a new one entirely as is done here, or just returning none, which basically cancels this even being passed through).

> Having axes configured in this way prevents you from having to write code to handle both negative and positive cases. You just code to handle a single axis value.

But how do you handle different mappings to different parts of the axis, or via combinations with other inputs (holding ctrl+moving the axis for example, which is trivial via one of the combinator events in my system).

**Comment by Xaeroxe** [comment]
Thank you for the code examples.  `/dev` looks like a unix file path but I see now you didn't intend it that way. (I'm admittedly not terribly well versed in how to interface with the contents of the `/dev` folder which could be the source of my confusion.)

Our current system does not support mapping combinations, this is true.  I didn't really consider it to be a priority when I designed the system but there is certainly room for improvement there.  Our mappings are expressed via a Ron file, which looks like this:

```Rust
(
    axes: {
        "horizontal": (
            pos: Key(A),
            neg: Key(D),
        ),
        "vertical": (
            pos: Key(W),
            neg: Key(S),
        ),
    },
    actions: {
        "jump": [Key(Space), Key(Up)]
    },
)
```

This allows devices to be mapped to actions.  I think we have similar solutions to the problem, just with differences in implementation details.

**Comment by Xaeroxe** [comment]
@OvermindDL1 I still don't entirely understand what you were using as a backend that permitted such incredible diversity in input devices.  Like I see how you're mapping the devices and naming them, but how did you get the data from them in the first place?  I'd be very interested in a backend that's that powerful.

**Comment by OvermindDL1** [comment]
> Thank you for the code examples. /dev looks like a unix file path but I see now you didn't intend it that way. (I'm admittedly not terribly well versed in how to interface with the contents of the /dev folder which could be the source of my confusion.)

Heh, yeah it is just part of my virtual filesystem in my engine that everything is bound to.  Hardware devices are bound inside `/dev` in various sub areas based on their tags, even the screen is too, any node can be created anywhere, and as such I put players in `/player/#` for player specific options like keybinds and action mapping.  Even the loaded level (and all levels metadata) is available in `/level` where the current active level is always available at `/level/current`, which also encompasses an ECS world (which might have further ECS instantiations inside it as well, or even elsewhere).  It is a very dynamic system, designed to be highly efficient yet easily scriptable (scriptable interfaces are not as efficient obviously, but useful for modding and so forth).

> Our current system does not support mapping combinations, this is true. I didn't really consider it to be a priority when I designed the system but there is certainly room for improvement there. Our mappings are expressed via a Ron file, which looks like this:

Yeah mine loads from a config file for initial setup but it can dynamically rebind and remap on the fly, like 
the player's `/players/0/forward` whatever gets sent to it then gets forwarded to whatever vehicle the player 0 is currently piloting, and this gets dynamically rebound as they enter/exist vehicles, and those vehicles do what they wish with that information.

> @OvermindDL1 I still don't entirely understand what you were using as a backend that permitted such incredible diversity in input devices.

It is actually pretty stupid-simple, and I've detailed it... somewhere here on github, let me see if google can find it...  Look through these maybe for some history where I talk about the system (I'm having trouble finding the specific post that I made once that spoke about the infrastructure..., that last one might be the most detailed public one I've got around to making...):
https://github.com/amethyst/amethyst/issues/229
https://github.com/MovingBlocks/Terasology/issues/2551#issuecomment-286445502
https://github.com/amethyst/amethyst/issues/177

But it basically all revolves around the getNode/setNode calls along with their atom64-based mappings ([this is my atom type](https://github.com/OvermindDL1/OverECS/blob/master/StringAtom.hpp), it encodes a restricted set of characters at compile time to a 64-bit or 32-bit integer depending in a reversible way, basically a globally unique enum by name that is just an integer, so even in C++ you can `switch` on it with ease since it is just an integer at compile-time).  Different nodes have different functions, and usually you'd cache the nodes as much possible to prevent having to do the lookup for them dynamically, and as long as you do that then they remain very fast with the calls being fairly direct (especially if you know the type of the node you are working on, thus skipping even the virtual dispatch).

> Like I see how you're mapping the devices and naming them, but how did you get the data from them in the first place?

Different ways.  Like `/dev` is a generic 'DeviceManagerNode`, so any calls or pathing into `/dev` is actually a call into that instanced node.  Doing something like `/dev/keyboard` does a path into that node and it knows what "keyboard" is, basically mapping to a list of physical keyboards (DeviceNode's (maybe input, maybe output, maybe both) that are tagged as 'keyboard', in addition to whatever else they are).  Something like `/player` is actually a `GenericNode`, I.E. just a dummy container that you can store other things on.  You can add any node about anywhere (even the same node in multiple places) and link all you want.  Something like the LevelNode (like at `/level/current`) does not, for example, actually make a link of all its internal things, rather when you do something like `/level/current/named/BossMonster` it knows that you ask for the 'named', which returned a proxy object to the named list in that level, and looking up `BossMonster` on it then returns that monster (you would then probably cache that link so you don't have to look it up every frame or whatever, I cached about everything I could even though it is actually pretty fast as it is).

> I'd be very interested in a backend that's that powerful.

It's *really* old, something I'd worked on for well over 15 years now (1999 I think is when I started if I remember right) and written with very non-modern C++ code (C++98 whoo!) but it was wonderfully powerful.  But like many people I made a lot of little demo-games and sandbox games but I was really just an engine developer (I don't have a designer bone in my body).  It ran on Linux, Windows, and Android.  I also incorporated build systems for Mac and iOS but I never tested them.  I always intended to get it working on emscripten but my free time the past few years dropped significantly (real-life hits again!) so I never got around to it.

**Comment by OvermindDL1** [comment]
Also there was a config file that did a basic mapping of nodes -> nodes with an optional filter (looked up in a pre-built named list, or you could define your own via luajit in the config), so that is how the basic system got set up, just loaded the global mapping config (which also injected settings into nodes to control the starting resolution and so forth, *everything* went through the nodes).

**Comment by torkleyy** [comment]
@OvermindDL1 Do you have a link to the source of your engine?

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Do you have a link to the source of your engine?

Not online, it exists in my SVN repo on one of my many hard drives stored in a box now (in addition to the crazy amount of code I had on that SVN server as well, this was well before git existed, svn was new when I set it up as I migrated from CVS).

I started to re-make the ECS part [here](https://github.com/overminddl1/overecs) in more modern C++ and using it as an example of my ECS design when specs was in development but it is only an hour or two of work.  The stringatom file is from my old project though as I keep pulling it out and using it in a variety of things (being able to basically 'switch' on strings is very nice, plus it makes dynamic keyed lookup wonderfully blazing fast).  I've only recently (in decades terms) been open sourcing almost everything I made, I used to be very self-conscious about my code quality before I'd let anyone see it (nowadays I don't really care, I figure any code public is better than missing poor code, as shown by the diluge of random crap on my github, and even then I have a *lot* more private on bitbucket still...).

The reason I keep hanging around amethyst/specs is because specs is the closest ECS to the one I built long ago (mine still had a few big differences, especially in the abilities of custom container types as I can do pretty much anything I can think of, even optimizing position/velocity with very efficient and linear SSE as shown in one of my overecs timing tests in that repo using Eigen, I've still yet to find a math library of similar quality and efficiency to Eigen in the Rust ecosystem), plus I used an Event system (with optimized direct-call paths in a few hot areas, not completely dynamic) significantly more than Amethyst does (you can see a tiny hint of my old event system in overecs, but it is not fleshed out at all, but you can see how some of the hot paths were optimized to direct calls for example) and all that worked wonderfully well when integrated into my virtual filesystem.

Really though, I keep poking amethyst as I really do not want to make an engine anymore and I actually want to make something using an engine of the style that I want (I've made plenty little test things in everything from godot and love to UE3/UE4 and Unity to Torque (back when it was fairly new) and more) and amethyst is the closest one out, so I just try to keep guiding it as much as I can with the little time that I have (I still need to learn Rust better, but its lack of anything remotely like the power of C++ templates prevents a lot of the assembly optimized code generation and expression template style builders that I'm used to relying on, I eschewed those in the overecs repo to be easy to read by non-C++ people, but traditionally I'd use heavy templates to not have to specify every-little-thing-manually, I'm very much a Lispy style C++ coder, I'm addicted to self modifying and optimizing code and Rust is just *so* amazingly verbose in comparison).  ^.^;

**Comment by Xaeroxe** [comment]
@OvermindDL1 I appreciate your experience and your desire to help.  So, precisely what is it that you want us to do with this input system?  What is your proposal?  I see that you feel my Virtual axes emulated with buttons are an unnecessary complication.  My view on this is that they aid in game programming, they're already there and in my opinion it's only really the smallest modicum of architecture, and it is unlikely to spiral out of control and make future development difficult.  If it truly does make future development difficult it's fairly easy to remove them as the implementation is under 100 lines.

**Comment by OvermindDL1** [comment]
I'd definitely say not to have the input system know or care about anything beyond what input handles, and action mapping is not part of the input system but rather should use the input system.  Input really should just expose boolean, relative axis, and absolute axis, nothing else (other than helpers like giving ranges or whatever else, but the raw values should be the raw values).  The action mapping system, whether a dedicated system or a set of event links with filters like in mine is what should handle actual mapping like mapping part of an axis to a button or so (and even then it should not map to an actual 'button' but rather just to some action inside the engine, like 'forward' or whatever the engine user wants to name it).

**Comment by Xaeroxe** [comment]
Alright I think we might be having a bit of a vocabulary problem here honestly.  What you refer to as an input system seems to be already taken care of by our glutin backend, the functionality that we are providing in `InputHandler` is entirely meant as convenience functions.  What I've been working on is enhancements to those convenience functions.  @torkleyy earlier in this thread talked about wanting to have joysticks and the like as well, which would require us to get a backend to receive the joystick input in the first place.  So it seems like what you're calling the input system, we are actually obtaining from other libraries.  Then we just write convenience functions on top of those to provide further helpful abstraction.

**Comment by torkleyy** [comment]
I think @OvermindDL1 still has a point. My ultimate goal would be to get rid of glutin events (as in the engine handles them for the user). So if we don't have the events, we probably want raw input as described by @OvermindDL1. However, I don't think we should have such a node system, because we already have something else instead: ECS resources. Why not just have a `Devices` struct instead of `"/dev"`? I see two advantages here: 1) By clearly separating them, we can easily have concurrency 2) Not everything needs to be a hash map. Sure, there are some things that need extreme flexibility, but this way, we can decide where we need it, plus we have stronger typing.

**Comment by OvermindDL1** [comment]
> What you refer to as an input system seems to be already taken care of by our glutin backend

Oh no no, not at all.  Glutin would be more like the SDL side of my engine (SDL2 runs underneath it).  InputHandler on the engine level is purely an even pusher.  But I get inputs from the hardware in a variety of areas and they all get pushed into the VFS mapped straight to boolean/absolute/relative bindings, which those then get mapped to actions (with filters quite often).  I absolutely do not *ever* let the backend raw events from whatever hardware systems leak into the engine level, they all get massaged into the 3 standard types of boolean/absolute/relative (do note, a keyboard key is mappable and is exposed as both a boolean and an absolute as one example).


An aside, it looks like glutin has some issues...  It's not sending me mouse buttons 3 and 4, only 0, 1, and 2 work (left/right/middle, but not back/forward).  And my F keys above F15 are not appearing as F* keys as the bindings appear to be missing, but they do at least come as an unknown mapping of raw integers (198 for F20 for example).  What is with the incomplete key mappings?

**Comment by OvermindDL1** [comment]
Hmm, even more interesting, my primary keyboard's F20 is mapped to integer `198`, but my secondary keyboards F20 is mapped to `13`, yet something like F15 is mapped to `F15` on both in the glutin key map.  Glutin seems bugged, I'm finding a lot of issues with its hardware input systems...  o.O

Also how do dyou tell the difference between different hardware inputs.  My keyboard and mouse extra keys are all coming in as just keyboard events, and I'm not seeing anything on the `KeyboardInput` event that let's me tell the difference between them.  For example:
```
# Pressing F15 then F16 on my keyboard:
Unhandled Keyboard Event: F15
Unhandled Keyboard Event: F15
Unhandled unknown event: KeyboardInput(Pressed, 194, None)
Unhandled unknown event: KeyboardInput(Released, 194, None)
# Pressing F15 then F16 on my mouse:
Unhandled unknown event: KeyboardInput(Pressed, 15, None)
Unhandled unknown event: KeyboardInput(Released, 15, None)
Unhandled unknown event: KeyboardInput(Pressed, 16, None)
Unhandled unknown event: KeyboardInput(Released, 16, None)
```
I cannot tell which event comes from which device (I've not even tested my half-dozen other input devices yet but I expect similar issues here as well...)...  This is very very wrong...

**Comment by OvermindDL1** [comment]
Ahh, hold on, ignore me, found the device_id, I'm used to using a UUID for hardware devices.  This brings me to another thing then, `DeviceId` seems to be an integer, however this can change as the devices are removed and re-added, the UUID should always be the same for a given device (hence why I use it as my device ID in my engine).  Any reason the system UUID of the hardware was not used as the identifier?

**Comment by OvermindDL1** [comment]
Hold on, no, let me check something here...  No it does not seem to be exposed, how do you determine the device_id then?  >.>

**Comment by OvermindDL1** [comment]
> However, I don't think we should have such a node system, because we already have something else instead: ECS resources. Why not just have a Devices struct instead of "/dev"?

Entirely plausible.  I'd see no issues with that as long as it was descriptive enough.

> I see two advantages here: 1) By clearly separating them, we can easily have concurrency

My engine was *highly* concurrent.  Even event handling was quite concurrent platform-dependent (pushed events into an atomic queue that was processed by a System 'sometime').

>2) Not everything needs to be a hash map. Sure, there are some things that need extreme flexibility, but this way, we can decide where we need it, plus we have stronger typing.

GenericNode was a map (not a hash map as I optimized for the general case of small count where hashmaps, at least C++'s/Boosts, was slower on in comparison, but there were other generic node types with specific storages, like array's was a common one that was accessed via index), but most nodes were not.  Like doing `/dev/keyboard` accessed the 'keyboard' atom on the 'dev' node, which just returned the proxy that wrapped the keyboard definition array.  Very few things were actually straight-out map's to look up nodes, one of the only ones were the player action mappings actually.  Even then they only had a fairly minimal start-up cost as you could hold on to the node elsewhere and just access it directly from then on:
```cpp
// At system startup:
Node *forwardNode = system->getNodeByPath("/player/0/forward");
// Then just use `forwardNode` from here on out, no map lookups performed
```

**Comment by omni-viral** [comment]
Let me put in my two penny worth.
I think users need only two kinds of abstractions, not three: `Event`s and `State`s. Where mouse relative movement is `Event` and absolute position is `State`, Keystroke is `Event` and key currently down/up is `State` etc. And ability to map core `Event`s and `State`s to user-defined to serve as bindings.
So `InputHandler` should be parameterized by user's `Event` and `State` types and initialized with mapping functions. `InputHandler` then use those mappings and throw both raw and user-defined `Event`s at each frame and gives access to both raw and user-defined `State`s.
This way seems more flexible to me than using `String`s. As it allow to treat key pressing and releasing as different event or same event with different payload depending on provided mapping.

**Comment by omni-viral** [comment]
As it could be confusing. 
`State` and `Event` above are traits, not types.
Tuple of `State`s is `State` itself.
Tuple of one `Event` and `State` is `Event`

**Comment by Binero** [comment]
I do like the idea of being able to bind to both states and events, for at least digital input. One could bind to a key press, a key release, the state of a key being pressed or the state of a key being released.

**Comment by Xaeroxe** [comment]
This is mostly fixed by https://github.com/amethyst/amethyst/pull/385

One remaining task I see here is that we still don't have any good abstractions over different axis types implemented.

**Comment by Xaeroxe** [comment]
So, abstracting over different axes is only really helpful if we have more than one axis type to abstract over.  To that end I made this issue: https://github.com/amethyst/amethyst/issues/414 and I'm going to close this one as it's developed a lot of baggage that's already been addressed.
