### ISSUE TITLE
[Discussion] Use cgmath as our official math library?

### ISSUE THREAD

**Issue by Rhuagh** [amethyst/amethyst#452]

**Comment by Xaeroxe** [comment]
On the contrary, I'd actually like to advocate for cementing cgmath as our official math library.  This has been discussed on gitter and I believe we're at a place where we can do this, if we commit to finishing Rhusics and integrating it into Amethyst.

**Comment by torkleyy** [comment]
Related:

* https://github.com/amethyst/amethyst/issues/200
* https://github.com/amethyst/amethyst/issues/236

**Comment by Rhuagh** [comment]
I agree with @torkleyy,  consistent. Rhusics use cgmath extensively, but I'm considering fixing that at some point. That's way in the future though

**Comment by Xaeroxe** [comment]
@Rhuagh Fixing in what way?  I'd argue usage of a math library is a huge boon to a project, not something that needs to be fixed.  Cgmath types provide way more expressiveness than any alternative I've seen.

**Comment by Rhuagh** [comment]
I want to remove it from interface

**Comment by Rhuagh** [comment]
But that requires generic consts

**Comment by Xaeroxe** [comment]
@Aceeri I'm also specifically interested in your feelings on this plan, as you've been working on the transform system which would be most heavily impacted by this.

**Comment by kvark** [comment]
Exposing everything with `cgmath` is certainly convenient for us as developers, but in the end this is going to alienate a large group of Rust users who prefer other math libraries. I believe the latter is more important.

**Comment by Xaeroxe** [comment]
I'd argue it's better to be opinionated and helpful, rather than pushing the responsibility for math onto the user.

My priority is to produce an easy way to make games, I need the computer to do math for me and I'm not really that picky about whose code does the math, I just need the math done.  I like cgmath because it allows me to do the math with as little mental effort as possible.

If someone refuses to use Amethyst because of our choice in math library I'd argue they have their priorities in the wrong place.  If anyone has specific reasons why cgmath genuinely hurts our downstream use cases then maybe we should consider another library but we have to pick something.  Indecision is hurting us and our users.

**Comment by Aceeri** [comment]
I don't see much reason why we shouldn't just use `mint`.

**Comment by Xaeroxe** [comment]
@Aceeri Differing versions in use throughout the ecosystem have hampered mint's ability to effectively convert across crates.

**Comment by Rhuagh** [comment]
Mint has no math, only types, which means in some cases you will be forced to expose other types unless you want to duplicate code.

**Comment by kvark** [comment]
@Xaeroxe 
>Differing versions in use throughout the ecosystem have hampered mint's ability to effectively convert across crates.

What are you talking about?
0.4.1 and 0.4.2 are not different versions, there is no problem if all the ecosystem depends on different 0.4.X versions, since in the end cargo (with help of semver rules) will just pick the highest patch version for all.

> If someone refuses to use Amethyst because of our choice in math library I'd argue they have their priorities in the wrong place.

We don't need to confront the users, we need to serve them.

**Comment by kvark** [comment]
@Rhuagh 
> Mint has no math, only types, which means in some cases you will be forced to expose other types unless you want to duplicate code.

What do you mean by "other types"? As long as it's not as opinionated as cgmath/nalgebra/whatever, other types are totally fine.

**Comment by Rhuagh** [comment]
Right now as an example in trying to write code to interpolate decomposed transformations, and the public api for that will either have to duplicate the code for 2/3/4d vectors, expose cgmath or nalgebra or create an entirely new set of types to be abstract over.

**Comment by Xaeroxe** [comment]
@kvark 

> What are you talking about?

I'm referencing the difficulties I experienced the last time I tried to use mint types throughout amethyst.  We haven't been able to keep all of our dependencies up to date due to conflicting requirements throughout the project so we're mainly experiencing conflicts between versions of mint, cgmath, and gfx.

> We don't need to confront the users, we need to serve them.

Providing types that are easy to combine and re-use for math operations is better service than requiring the user to convert the types for every operation.  Being able to write `transform.position.x += 5.0;` is better service than having to write `transform.position.0 += 5.0` Providing simpler APIs because we have a chosen math library is better service than complicating interfaces because we can't pick a math library.

Both of those are preferable to enabling people to use whatever math library they want, which by the way they can still do because cgmath provides conversions to std library array types, so if they absolutely must use another math library, they still can.

When I say users have their priorities in the wrong place what I'm referencing is that I anticipate most people just won't care, so long as they have a way to tell the computer to do the math that they need to do there isn't really a huge practical reason to dislike cgmath.

Providing an opinion is not confrontation, it's getting the job done.

**Comment by kvark** [comment]
@Xaeroxe 
> we're mainly experiencing conflicts between versions of mint, cgmath, and gfx

Ok, I see/recall now. This is not what you said earlier (with `mint` in context):

> Differing versions in use throughout the ecosystem have hampered mint's ability to effectively convert across crates.

`Mint` versions don't conflict here, it's `cgmath` that does, because you'd need `cgmath-0.15` to support `mint`, and `gfx-0.16` is only integrated with `cgmath-0.14`. I don't believe sticking with `0.14` for long is something you can afford anyway, and not requiring the usability of the engine to be bound to changing math versions is precisely where `mint` would help. FWIW, `gfx-0.17` will `mint` integration *instead* of `cgmath`.

> Being able to write transform.position.x += 5.0; is better service than having to write transform.position.0 += 5.0

True. And `position.x` is as true in `mint` as it is in `cgmath`/`nalgebra`.

> That is preferable to enabling people to use whatever math library they want, which by the way they can still do because cgmath provides conversions to std library array types, so if they absolutely must use another math library, they still can.

Sure, but it's almost like stepping into `unsafe` territory, given the inconvenience of all the casts and the semantics erasure that fixed type arrays give. Certainly not very attractive.

> When I say users have their priorities in the wrong place what I'm referencing is that I anticipate most people just won't care, so long as they have a way to tell the computer to do the math that they need to do there isn't really a huge practical reason to dislike cgmath.

You'd be surprised how opinionated users can be about math libraries :) Nobody wants leave the comfort zone of their most used math choice, and for the most part people are fine with sticking to whatever choice they made on day 1.

**Comment by Xaeroxe** [comment]
Mint is better than what we currently have, I can agree to that, if we can resolve the versioning problems we've been having.  However cgmath takes that a step further and also permits easy use of the types for math operations without burning cycles and lines on conversions.  Not to mention use of cgmath resolves the problems @Rhuagh has been encountering.

Most of our popular math libraries have mint support anyways, so even if we don't convert with std library arrays you can still convert with mint types.

> You'd be surprised how opinionated users can be about math libraries :)

I guess the problem we've reached at this juncture is we're both speculating on what users will care about.  We don't have any good data one way or another.  One thing I will say is that most of the opinions I've seen expressed at least here in the Amethyst community have been in favor of simply not having an opinion.  However those same people I've seen also convert to cgmath types when they need to do math operations.  So it seems we all have a bunch of anxiety about acting on our opinion but most of us here at least do use cgmath.

That's all the data I have unfortunately, and I'm not really sure how to get more.  Should we host a poll?

**Comment by Xaeroxe** [comment]
I've made this survey: https://goo.gl/forms/5ryanGWHzqzc0rgH2

Can you give me a 👍 on this comment if you think the survey questions fulfill our objectives here?

**Comment by minecrawler** [comment]
So, the biggest issue at hand is that we still cannot get all software on a shared Mint version. We should update cgmath in order to get Mint 0.4 support. gfx-rs will go full-mint in version 0.17, but will that be Mint 0.4 or Mint 0.5? Will Rhusics offer Mint and if yes, which version of that? Maybe, a tl;dr would be: The ecosystem at the moment is still too young and unstable for a big applications with many dependencies (like a game engine) to use growing standards.

Personally, I think Mint is the way to go, but at the moment very troublesome. cgmath is Amethyst's math lib of choice (as far as I can see). So, I wonder if it would work out to either expose cgmath or std types in APIs until Mint stabilizes (v1.0.0) and other important dependencies (like gfx) take up the stable standard. Then we could switch over stuff to Mint 1.0, too - ideally before Amethyst v1.0.0. After the switch to Mint, games should either compile out of the box or just miss a `.into()` to make them compatible.

**Comment by Rhuagh** [comment]
I think we can get away with using mint or raw arrays in the interfaces of mandatory or near mandatory crates, and let auxiliary crates be opinionated

**Comment by Rhuagh** [comment]
Rhusics can't go mint for the foreseeable future simply due to its dependencies

**Comment by kvark** [comment]
@minecrawler I think the problem with mint-0.4 and imminent upgrade to 0.5 is the main adoption blocker at the moment. We'll try to make sure that all the next versions of cgmath, nalgebra, and gfx depend on mint-0.5.

**Comment by minecrawler** [comment]
@kvark which means that Amethyst has to update all of those dependencies before it can use Mint 0.5 itself. I don't know how much work that involves, but my guess is that at least gfx-rs, is a big change (especially switching to gfx-hal). When Amethyst finally is there, maybe you already released Mint v0.6. It is always difficult to follow a moving target.

**Comment by kvark** [comment]
@minecrawler 
> which means that Amethyst has to update all of those dependencies before it can use Mint 0.5 itself.

Yes. Technically, you will be able to do it in one go. It's only gfx-rs and cgmath, there is not a whole of "all of those" :)

> I don't know how much work that involves

Going from mint-0.4 to 0.5 would require next to no work. It's just a `RowMatrix` semantics fix.

> but my guess is that at least gfx-rs, is a big change (especially switching to gfx-hal).

This has nothing to do with gfx-hal. Going from gfx-0.16 to gfx-0.17 will be a minor tweak/change for you.

> When Amethyst finally is there, maybe you already released Mint v0.6.

Maybe? In any case, we'll have fewer version changes than cgmath, gfx and friends.

**Comment by torkleyy** [comment]
I think the question here is what advantage we get by using mint over arrays. There's one disadvantage, that the API will have to change with new mint versions. What are the advantages? The only one I can think of is stronger typed parameters.

**Comment by Rhuagh** [comment]
Things like alignment, row vs column major and not much more I think

**Comment by torkleyy** [comment]
So personally I prefer arrays to be honest, because they can be constructed easily and also converted by doing `.into()`. Additionally, and this is also a big advantage, they don't require a major bump because there's an update of some library (mint).

**Comment by OvermindDL1** [comment]
I've not done much (any?) Rust metaprogramming yet, but this issue is pretty trivial in C++.  Like take, oh, Boost.QVM (QMV?), it is a generic game-orienting quaternion/vector/matrix library that although it defines it's own types, it can use types from any other math library as well, including weird meta-template libraries like Eigen.  It does this just by tagging the remote types with a new type in a local namespace that allows the Boost.QVM calls to work transparently between it's own types, Eigen, and whatever else you can think of (it has built-in support for quite a lot, and it is pretty trivial to add in new ones).  Does Rust not have such trivial functionality?

**Comment by Xaeroxe** [comment]
So I think I may have a compromise that serves everyone's needs.  This has already been discussed on gitter but I'm also posting it here to make sure the info reaches everyone.

We need cgmath to write the best amethyst we can, but we also don't want to inhibit people from using other math libraries if the need arises, so if we use cgmath extensively and also enable the mint feature for it, then users can convert to mint types and to array types, whatever suits their fancy, and we can use cgmath internally.

**Comment by minecrawler** [comment]
Does that mean that we expose cgmath or Mint?

**Comment by Xaeroxe** [comment]
We expose cgmath compiled with the mint feature.  

Relevant PR: https://github.com/amethyst/amethyst/pull/462
