### ISSUE TITLE
Rethink example strategy

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#468]
Currently, examples get added by PRs introducing a feature, showing how to use that particular feature. While this is a good strategy for smaller crates, it's worth considering another strategy. The numbering of our examples implies a recommended order to look at them, but this impression gets proven to be wrong once you see custom assets before loading a glTF scene. So maybe the question I'm asking here is:

Do we want the examples to be kind of like a walk-through, a tutorial series for Amethyst, eventually accompanied by the book, or should they, without any implication of an order, just show how to do X?

**Comment by Rhuagh** [comment]
The current examples should be without order imho, and demonstrate individual features. For tutorial content I would suggest we create a new crate for it `amethyst-tutorials` or some such

**Comment by Rhuagh** [comment]
New project was what I meant btw, under the amethyst organisation

**Comment by torkleyy** [comment]
@Rhuagh In which relation would the book and the tutorials be?

**Comment by Rhuagh** [comment]
Symbiotic

**Comment by Xaeroxe** [comment]
Do we need a book if we have the tutorials?  I'm going to draw a parallel to the Rust book, because that's likely what we're basing that idea on.  The Rust book works great.. for Rust, because Rust introduces a lot of new concepts and mandates that kind of "Full course" on how to use it, but a tutorial structure might actually work better for us because for the most part we just need to show off our APIs and how to use them.  It might be helpful to have things like "Here's what an ECS is and how to use it" but beyond our ECS we don't introduce a ton of terribly confusing topics imo.

**Comment by Aceeri** [comment]
I think tutorials and a book could go hand in hand. The book could be just in depth into certain features about what they do, how to use them (mostly isolated from any actual application), while the tutorial is the feature in action.

**Comment by Rhuagh** [comment]
I agree with @Xaeroxe, beyond ECS, we really just provide a bunch of separate crates that you can use with `specs`, so it makes sense to describe how to work with those APIs for the most part. 

I do think we should have the book be kind of the introductory content, like the first "part" of the tutorials, and in the last chapter, we point out the tutorials project for more information.

**Comment by Rhuagh** [comment]
The book could live in the tutorials project aswell.

**Comment by Rhuagh** [comment]
Let's keep the book in the main crate for now, we can always revisit this later.

**Comment by torkleyy** [comment]
I think the example strategy has been resolved and applied by @Rhuagh's PR. Thank you!
