### ISSUE TITLE
[RFC] Creating a cross-platform input library

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#481]
So, currently Amethyst is using the glutin+winit libraries for window management.  This has become problematic as of late as we're discovering the input handling capabilities of this library are not quite up to our needs.  DeviceEvent is too raw and too opaque to be very useful and WindowEvent is very restricted in the kinds of input it can receive.  An external crate just for input also isn't really an option as input events are received via the window's event loop on nearly every major platform.  So we have a few choices:

- Make PRs to these libraries to improve the input abstractions.  @tomaka has previously indicated in multiple issues on these projects that he is opposed to a high level input abstraction, so I'm not sure how much progress we can make there.  To be more precise, we require
  - A fix for https://github.com/tomaka/winit/issues/338
  - Knowledge of which DeviceId correlates with the Mouse
  - Preferably the ability to retrieve a human friendly device name associated with a device ID
  - A more shallow event hierarchy would be nice but is not essential.
  - A fix for https://github.com/tomaka/winit/issues/330 would be nice but is also non-essential.

- Fork these libraries and make the changes we need.  This is problematic as we'd be breaking compatibility with crates like `gfx_window_glutin` and the like.

- Use rust-sdl2, which while battle proven does have a few hard to debug memory issues that pop up occasionally, and it may not have the best support for modern graphics APIs such as Vulkan or Metal.

It'd be nice if @tomaka could weigh in here and tell me if our wishlist for winit+glutin is something they consider worth pursuing or not.  If not we may have to consider using SDL2 while we code together some kind of replacement, which could itself take a while.

**Comment by torkleyy** [comment]
I'm opposed to maintaining our own fork, that's just duplicated effort and it would require too much time.

**Comment by Xaeroxe** [comment]
@torkleyy while I agree there are definitely downsides to that, I'm not completely certain where else to turn.  With SDL2 we're locked in the past due to the usage of C++ and outdated graphics APIs, but with glutin/winit we have suboptimal input and no way to do anything about it.

**Comment by tomaka** [comment]
The reason why I'm "opposed" is that I don't want to add yet another buggy and half-implemented feature.

Here is what will happen if I accept this. First someone will open a PR that implements things on Linux, and put giant TODOs everywhere in the other backends. At some point people will start pinging me or opening issues asking why are input doesn't work on Windows.

Then someone will want to write a Windows implementation, and we will realize that the API of Windows cannot be plugged in with the existing API that winit exposes. Several long unproductive discussions will follow (think corporate meetings) and will lead nowhere because no-one has an idea what they're doing when it comes to windowing systems.

At the same time people will also open issues because it turns out that X is an incredibly buggy system and the implementation of are devices will  only work on half the machines out there. People with poor knowledge of the inner architecture will open pull requests of poor quality that need to be reviewed.

Now if you want to manage everything related to raw devices in winit, then go for it and write an APP and implement it! But I don't want the hassle.

**Comment by torkleyy** [comment]
If what you are sugesting is that we build an API on top of the platform-specifics that winit exposes (`winit::os`), I'm all for it.

**Comment by Rhuagh** [comment]
I think basically what we need is to replace the `EventsLoop` and `Events` parts of `winit::platform`. It should be possible to create a common abstraction over input and make a winit integration crate which basically reimplements those parts of `winit` but with our common types.

**Comment by Rhuagh** [comment]
I think the way forward is:

* Make PRs into winit to fix the outstanding issues:
  * Fix `DeviceId` so it's actually usable for all platforms
  * Remove the opaqueness of `DeviceId` so we can test in a headless environment, and possibly enhance it so a human readable name can be extracted from it.
  * Add a `DeviceType` abstraction
  * Possibly make the event hierarchy shallow (not essential, just a quality of life improvement).
* Create new crates for external devices (gamepads etc) that feed into `winit`s event hierarchy

**Comment by torkleyy** [comment]
I fully agree with you @Rhuagh with the addition that I don't want `winit` to be a public dependency. Having a thin layer above it allows us to add features more easily, adjust the events and to upgrade it without bumping our major version.

**Comment by Xaeroxe** [comment]
So I totally missed the fact that `winit::os` is available to us.  That makes our lives so much easier.  I think we can do this :+1:

@tomaka suppose we create a thoroughly tested system that we can verify works on all supported platforms.  Would you be interested in integrating it into winit once we proved the solution was of sufficient quality?

**Comment by vitvakatu** [comment]
On behalf of Three-rs project I also interested in the idea of convenient input library. Perhaps I'll be able to help somehow :wink:

**Comment by tomaka** [comment]
> @tomaka suppose we create a thoroughly tested system that we can verify works on all supported platforms. Would you be interested in integrating it into winit once we proved the solution was of sufficient quality?

Yes!

(cc'ing @vberger @mitchmindtree @Ralith in case they have something to say)

**Comment by Xaeroxe** [comment]
@torkleyy has begun work on a new crate called winput.  I'll jump in and help out when I get back from vacation :)

**Comment by torkleyy** [comment]
Prioritizing this, it seems people are interested in it so I figure it's best to get an initial version ready ASAP.

**Comment by Ralith** [comment]
I'm the author of winit's current raw input APIs, and the X11 backend thereof. They're very much intended to be the smallest possible thing that can propagate lossless inputs and distinguish devices, leaving room for additional functionality to be introduced as needed. I've since determined that I need very little indeed, making it difficult to prioritize further improvements, so I'm happy to hear interest from others in improving things. It's important work.

I would strongly caution a high-level API effort not to focus myopically on xbox-like game controllers. Game input devices are a wide and diverse world, from joysticks to rudder pedals to radio panels and more, most of which *can* be encompassed by notions like axis positions, button presses, and switch states, but much of which *cannot* be encompassed by "six buttons, two sticks, and some triggers". Tools that fail to make allowances for unconventional or even merely customized controls are always disappointing.

The low level OS APIs for this game input devices are (almost?) universally garbage and care must be taken not to propagate their misguided assumptions to the ultimate detriment of users. I've spent a lot of time being angry about this, so if anyone wants to hear me rant at further length please do come ping me in #rust-gamedev.

**Comment by Ralith** [comment]
For example, this is a game input device:
![image](https://user-images.githubusercontent.com/104558/32401637-24bf3dd2-c0d0-11e7-8b1e-2e968f8042c9.png)

**Comment by vberger** [comment]
Regarding platforms, for wayland, the handling of raw input devices is somethings that is still very experimental and being discussed in the wayland dev mailing lists. From what I see there are basically two categories:

- keyboard/mouse/touchscreen/tablet devices are controlled by the wayland server, and there exists protocol extensions to obtain raw input from them (notably [contraining the pointer to a window](https://docs.rs/wayland-protocols/0.12.1/wayland_protocols/unstable/pointer_constraints/index.html), [obtaining relative motion for pointer events](https://docs.rs/wayland-protocols/0.12.1/wayland_protocols/unstable/relative_pointer/index.html) and [tablet handling](https://docs.rs/wayland-protocols/0.12.1/wayland_protocols/unstable/tablet/index.html))
- other devices (joysticks and similar) are for now to be directly opened from the device files (in `/dev`) by the app willing to use them, which I believe is already what most X11 game do anyway.

**Comment by torkleyy** [comment]
I'm trying out the Rust binding for `libinput` atm (`input.rs`), but it seems that dropping the context causes a segmentation fault :(

As far as I understood, `libinput` is only responsible for device events, and doesn't handle window events, is that correct?

**Comment by vberger** [comment]
`libinput` is the lib that has been developed by wayland devs to serve as raw input layer for wayland compositors. As such, I honestly don't know how much it can be used to obtain raw input directly by a client application.

For sure, you won't be able to use it to obtain keyboard/mouse/touchscreen events, as these devices are already exclusively claimed by the display server.

I don't know if/how libinput can handle joystick and other gamepads devices.

**Comment by torkleyy** [comment]
@OvermindDL1 recommended to use `libinput` IIRC and to fall back to evdev for gamepads, maybe they can explain?

**Comment by torkleyy** [comment]
Hm, seems that libinput is indeed unsuitable for this:

> libinput is not used directly by applications, rather it is used by the xf86-input-libinput X.Org driver or wayland compositors.

([Source](https://github.com/wayland-project/libinput))

**Comment by torkleyy** [comment]
After some experimentation, I've come to the following conclusion:

The main issue we have is that there's no controller support. `winit` does not provide such an API, **but:** while some events (window events) need to be provided by the windowing library, this is not true for device events (which gampad events are). This means that we can have a completely separate API for gamepads and it turns out there already is one ([gilrs](https://gitlab.com/Arvamer/gilrs)). It does only support Linux and Windows so far and it probably doesn't support gamepads like the one @Ralith showed us (yet), but it's pretty much what I was going to build.

### This is why I propose the following:

* Contribute to `gilrs` and extend it with support support for OS X and Android
* Fix the minor issues with winit (device id creation for testing, fix ids for Windows)
* Build a layer on top of both `winit` and `gilrs` which allows us to design the event types the way we like them

**Comment by Ralith** [comment]
Please don't assume everything is a gamepad. Even simple (and very common) joysticks are broken by that. There is an incredibly rich world of devices out there, but it is stunted by design decisions like that and everybody suffers :(

To elaborate on the wayland situation, [the latest info I've seen](https://lists.freedesktop.org/archives/wayland-devel/2017-April/033819.html) suggests that cooperation with the compositor, likely mediated through winit, will be mandatory for all input devices, not just mouse/kb. That is, unless wayland's plans totally change direction, a completely separate API *will not work*.

**Comment by torkleyy** [comment]
@Ralith I see your concern, but I'm not sure what you're suggesting. I'm proposing that we add support for more input devices by using `gilrs` which is both an improvement of the current situation and a starting point for supporting more devices. Whether we start with that library or I build an initial version which has limited support doesn't matter except for the fact that the latter one is more work.

> There is an incredibly rich world of devices out there, but it is stunted by design decisions like that and everybody suffers :(

I fully agree, but this is not a design decision. I want to provide support for as many devices as possible, but we need to start somehow.

> That is, unless wayland's plans totally change direction, a completely separate API will not work.

I didn't know about these plans, but if that's what the wayland devs are planning, we'll have to extend `gilrs` with functions that take the respective handles.

**Comment by Ralith** [comment]
I was concerned that gilrs did not seem to even express interest in more interesting devices, but on closer examination, it is considerably less gamepad-specific than its README first lead me to believe; I suspect it might in fact work for the above-pictured control box on non-Windows. In particular, its [`EventType`](https://arvamer.gitlab.io/gilrs/doc/gilrs/enum.EventType.html) enum, while clearly designed to privilege gamepads, is nonetheless capable of representing arbitrary button/axes not having predefined semantics. Cosmetics aside, to get richer data than that you need to start speaking USB HID directly (which is an interesting option to explore, but probably a deep rabbit hole).

Getting `gilrs` to play with the proposed wayland API will require care, as the events can only be received over the same connection as is associated with the window, i.e. the connection owned by winit. Probably no use thinking too hard about that until it's implemented, though.

**Comment by Xaeroxe** [comment]
@torkleyy I like your proposal, although I'd like to also request that we be sure to provide raw mouse input as well that is independent from the window so we can avoid things like mouse acceleration being added into the delta values.

**Comment by Xaeroxe** [comment]
> In case this proposal gets accepted, this issue shall be closed and a new one for the amethyst_input crate shall be opened.

I think we can do this now @torkleyy
