### ISSUE TITLE
Extend `amethyst_input` with gamepad support

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#488]
* [ ] Integrate [`gilrs`](https://gitlab.com/Arvamer/gilrs)
* [ ] Add OS X support
* [ ] Don't expose winit types but use own, flat and unified event types
* [x] Add support for raw mouse input / identify mouse device events

There are many ways to help here, for example by making small improvements to `gilrs`.

**Comment by Xaeroxe** [comment]
- [ ] Add support for raw mouse input

**Comment by torkleyy** [comment]
Added, feel free to add more.

**Comment by Xaeroxe** [comment]
@torkleyy So one of our goals is to completely remove our winit exposure, should we divide our new events into `InputEvent` (already existing) and `WindowEvent` (not yet created)?

**Comment by Xaeroxe** [comment]
I'd also like to propose creating a semantic distinction between `CursorMoved` and `MouseMoved`.  This distinction doesn't exist upstream but I feel it will be helpful to us.

**Comment by Xaeroxe** [comment]
I've also learned from browsing the winit source that DeviceEvents are only sent for the mouse on every platform except for the X11 Linux backend.

**Comment by Xaeroxe** [comment]
Relevant issue in winit: https://github.com/tomaka/winit/issues/338

**Comment by Rhuagh** [comment]
As long as MouseMoved gives a delta I'm all for it :)

**Comment by Xaeroxe** [comment]
Relevant PR for raw mouse data: https://github.com/tomaka/winit/pull/344

**Comment by Ralith** [comment]
> As long as MouseMoved gives a delta I'm all for it :)

It's worth noting that this is the *only* thing a correct impl can give, since mice are only capable of detecting relative motion.

**Comment by Rhuagh** [comment]
Well, yeah, but winit's WindowEvent::MouseMoved give absolute position for me, not delta.

**Comment by vitvakatu** [comment]
Because it's position in pixels inside Window

**Comment by minecrawler** [comment]
imho, an absolute value for the mouse position in a **WindowEvent** can make sense, because a window is 2D and usually the mouse is used for the cursor in that context (it means one less thing to take care of in the application code).

Since we are talking about having both, the window data and the raw data, wouldn't it make sense to choose a clearer name in Amethyst and just pass that data through? For example, the window event from winit might be called `CursorMoved`, passing the absolute cursor position in the window, while the mouse event from raw data might be called `MouseMoved`.

Ideally, there should be methods to set the cursor position, for example when a menu is opened and the cursor is un-hidden, it might be set to the last coordinates or just the center of the menu or screen, without sending out MouseMoved events.

**Comment by torkleyy** [comment]
:+1:

**Comment by Ralith** [comment]
> Since we are talking about having both, the window data and the raw data, wouldn't it make sense to choose a clearer name in Amethyst and just pass that data through? For example, the window event from winit might be called CursorMoved, passing the absolute cursor position in the window, while the mouse event from raw data might be called MouseMoved, delivering a delta.

That's the plan. See https://github.com/tomaka/winit/pull/344.

**Comment by torkleyy** [comment]
Why did you unassign me @Xaeroxe ?

**Comment by Xaeroxe** [comment]
I don't recall doing this so I guess it must have been an accident

**Comment by jojolepro** [comment]
Closing in favor of #414
Basic flat support has been added for controllers, with an optionnal SDL backend to pull the events.
We will continue the conversation there.
