### ISSUE TITLE
Roadmap links are broken because the page is no longer on the Wiki

### ISSUE THREAD

**Issue by distransient** [amethyst/amethyst#498]
What would be the best way to fix this, I'd be happy to write a quick PR if needed :)

**Comment by Xaeroxe** [comment]
This link is currently serving that purpose at the moment: https://github.com/amethyst/amethyst#vision

Where are the road map links specifically?

**Comment by Xaeroxe** [comment]
Ah I found them.  Thanks for the issue!

**Comment by distransient** [comment]
Be wary of the hidden one at https://github.com/amethyst/amethyst/blob/develop/CONTRIBUTING.md#useful-resources :)

**Comment by torkleyy** [comment]
A useful resource :smile: We don't have a specific written road map yet. But I think it would be useful to create one.

**Comment by oraknabo** [comment]
I'm not confident enough in my Rust skills to contribute any code to the engine ATM, but I'd like to volunteer to help in any way I can with the wiki, docs or website.

As someone just trying to get acquainted with this project, the information I've been looking for seems to be spread around in a lot of places from the design notes in the wiki pages to the RFC-tagged issues. Some things I've only been able to understand from reading the code and trying to run the examples myself.

I get that, at the stage this project's currently at, it takes a lot of work to keep documentation up to date with the codebase, but I think it's worth it to keep the project from seeming confusing or overwhelming to newcomers.

Once I'm more up to speed with the individual systems, I wouldn't mind contributing some examples, but until then, I'm available for anything else.

**Comment by torkleyy** [comment]
@oraknabo It's great to hear that you have interest in contributing! Also, documentation is an important part as you noted, but it's been ignored in the last months. However, @futurepaul is already doing a great job on the book currently which I really appreciate btw :) So it's slowly getting better.

I agree that the information should also be easy to find, but that's probably harder than it seems at first. We should agree on a strategy before proceeding. For one, if we add a new feature or change an existing feature, the design is mostly in the API docs (although not very detailed, and without any graphics). Some of this design is also important for writing games, so it'll probably make its way into the book, too. I have the feeling that if we simply write everything we currently have up as a wiki page, it gets outdated easily and we now have three places where the same thing is described. That would be a lot of work and slow down the development. And the other thing is that while we can all agree here that we need more documentation, that presumably won't help the situation too much by itself, since we all pick our contributions, our pull requests, our projects ourselves and do it on a voluntary basis.

**Comment by oraknabo** [comment]
@torkleyy Thanks for the reply. I just posted a new issue (#500) that relates directly to your suggestion about strategy.

**Comment by oraknabo** [comment]
What's the best plan of action here? 
An mentioned above, the roadmap is currently linked from the main README, CONTRIBUTING.md
I checked the website and cloned the wiki run a grep and found no other references.

Should we remove the links on these pages, create a page for roadmap & put some kind of "TBD/this is a stub" message on it or actualy start putting together a full page?

It seems like there was already an issue (#160) and a PR (#163) for a ROADMAP.md file in the repo, but the effort seems to have died out without any effort to reopen the issue.
