### ISSUE TITLE
Loaded sprites don't have transparencies

### ISSUE THREAD

**Issue by trsoluti** [amethyst/amethyst#510]
Hi, I've created a simple Amethyst example, based on the nightly build, to demonstrate loading a sprite from the assets and displaying it. My intent is to add it to the list of examples in the repository.

The example is here: [trsoluti/sprite_game.rs](https://gist.github.com/trsoluti/9cc7e1fb41635cb9ded6d240cc47869d).

However, the transparent parts of the logo show up as white instead of the background colour.

Am I doing something incorrectly? Or is there an issue in the renderer?

**Comment by omni-viral** [comment]
You use `DrawFlat` pass to draw your sprites. But IIRC `DrawFlat` doesn't support transparency.

**Comment by trsoluti** [comment]
Which pass should this example program use?

**Comment by Rhuagh** [comment]
We don't have any core passes for this yet, @Xaeroxe is working on this

**Comment by omni-viral** [comment]
@trsoluti you can do it yourself.
1. Copy `DrawFlat` code.
2. Replace `with_output` to `with_blended_output`.
3. Sort entities from far to near before drawing them.
4. Enjoy transparency 👍

**Comment by torkleyy** [comment]
> We don't have any core passes for this yet, @Xaeroxe is working on this

Are you @Xaeroxe ?

**Comment by Xaeroxe** [comment]
Yeah it will be part of my currently open PR.

**Comment by Xaeroxe** [comment]
A renderer pass supporting transparency in objects would likely be very similar to our current UI pass.  You'd need to 
- substitute the Z ordering for "distance from camera" 
- use the projection matrix of the camera instead of a "projection vector"
- Use actual Transforms instead of UITransforms

So ultimately it'd be a hybrid of the UI pass control flow and the DrawFlat drawing instructions, all being rendered to a BlendTarget rather than a typical target.  This also has the added benefit of supporting transparent rendering for 3D objects as well.

**Comment by antoyo** [comment]
Is this implemented by PR #574?

**Comment by torkleyy** [comment]
Yes, you can now use `with_transparency` on the pass you want to render with transparency.

**Comment by Rhuagh** [comment]
Remember to also enable transparency on the RenderBundle.
