### ISSUE TITLE
Document the animation crate

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#629]
I was trying to understand how the animation crate worked, and this was my attempt at understanding it.

Excerpt from gitter chat:

> Is this correct:
> 
> * [`Sampler`](https://www.amethyst.rs/doc/develop/doc/amethyst_animation/struct.Sampler.html):
> 
>     - `input`: Distinct "points in time" of the animation called "key frames".
>     - `output`: Given `input` has 10 key frames, the "output" should contain 10 `T` values which are "correct" values for the animation during those key frames.
>     - `function`: How to calculate an output value that lies between two key frames.
> 
> * `Channel`: (there's no concrete _type_ for this besides the associated type in [`AnimationSampling`](https://www.amethyst.rs/doc/develop/doc/amethyst_animation/trait.AnimationSampling.html), but the concept is there)
> 
>     A grouping of animatable attributes that are related (and usually affect each other).
> 
>     e.g. [`TransformChannel`](https://www.amethyst.rs/doc/develop/doc/amethyst_animation/enum.TransformChannel.html) has `Translate`, `Rotate`, and `Scale` because depending on the order of applying those operations, the final output will be different.
> 
>     And the following are possible channels:
> 
>     - `MaterialChannel`: different changes to the underlying textures (e.g. the albedo, etc.) affect the final rendered colour
>     - `TransparencyChannel`: How visible a texture is rendered (maybe this can be merged into the `MaterialChannel`?)
> 
> * [`AnimationSampling`](https://www.amethyst.rs/doc/develop/doc/amethyst_animation/trait.AnimationSampling.html):
> 
>     Trait to bridge the sampler function to the component (that contains the in-game values as input to the sampler function).
> 
>     What is [`BlendMethod`](https://www.amethyst.rs/doc/develop/doc/amethyst_animation/enum.BlendMethod.html) used for? Need to look at code to figure it out.
> 
> * [`Animation`](https://www.amethyst.rs/doc/develop/doc/amethyst_animation/struct.Animation.html):
> 
>     A grouping of individual parts &mdash; "nodes" &mdash; of the animation. Each node operates on one of the `Channel`s.
> 
>     What is the `usize` in the first element of the tuple? The [animation example](https://github.com/amethyst/amethyst/blob/develop/examples/animation/main.rs#L252-L259) just uses 0 for all of them.
> 
>     I have no idea what the `AnimationHierarchy` is, I got lost in the words.

`JadeSnail`:

> I think BlendMethod tells you what happens when you have several animations modifying say the Translate of the same entity
>
> Namely, with BlendMethod::Linear, you get an average of all the animations, and with None, only the last animation applies
>
> See https://www.amethyst.rs/doc/develop/doc/src/amethyst_animation/systems/sampling.rs.html#71-87

`azriel91`:

> ah yeap, and that's when the first tuple element of each of the animation nodes adds up to non-zero. The code says it's a weighting; I can tell what it does, but not sure when to use it.

---

I'll open a PR (probably tomorrow) with the content tidied up, but please teach me if I have misunderstood something :bowing_man:

**Comment by Rhuagh** [comment]
> @azriel91 ok, so conceptually if you look at animation from the bottom up, you can view it as controlled mutation of attributes of objects over time, using a predefined function
So, in amethyst, a Sampler is the lowest level working block, that defines the function, and what attribute or set of attributes the function mutates
the Channel is the set of attributes that are controlled with a single function call
so for Transform, we want to be able to mutate scale, rotation, and translation individually, which is why we define a TransformChannel with those three variants
a Sampler consists of either a predefined function (Linear, CubicSpline) or a boxed function that the user defines
and it also consists of the input and output values for that function (which can differ based on the function)
you can imagine the mutation function as fn(Time) -> ChannelValue

Simon Rönnberg @Rhuagh 18:41
if you look at the linear interpolation as an example the input and the output Vecs will be the same size, but for CubicSpline for example the size of the output Vec will be three times the input
this is because the CubicSpline function needs the in and out tangents at each interpolation point in addition to the actual point itself
so, that's the lowest level blocks
the next step up is Animation which defines a set of samplers that should always run together as a unit. each unit in the set is defined as a node index (will come back to that), a channel on that node, and the sampler to apply to that nodes channel

Simon Rönnberg @Rhuagh 18:47
the node index is used for animations that are defined on an entire entity hierarchy, but because Entity is an ephemeral value, and animations need to be possible to store on disc (which we won't be able to do with Entity), the animation use an AnimationHierarchy to define the link between the node index and Entity
so, Animation + AnimationHierarchy defines what Samplers will be run on an entire Entityhierarchy
if you look at the gltf example, that runs animations defined in the gltf file on an entire set of entities
the setup code for that is in the gltf crate (in the system and the loader)

Simon Rönnberg @Rhuagh 19:00
the AnimationHierarchy is usually attached to the "primary entity" for an animatable hierarchy
say you have a dragon monster, that is defined by a skinned mesh, that have a skeleton with 10 joints
each joint will then be an Entity, defined in a scene hierarchy using Parent links
the skeleton will then likely be attached to a root Entity that the game systems interact with to control the overall state of the dragon as a whole
the AnimationHierarchy attaches to that root Entity, and defines the link between the node index in Animations for the dragon and the joint Entitys in the scene graph

**Comment by Xaeroxe** [comment]
Fixed
