### ISSUE TITLE
Broadcaster is lacking features

### ISSUE THREAD

**Issue by Emilgardis** [amethyst/amethyst#74]
With PR #67, there is no way to access the world, which would have made it possible to add resources, `Systems` and the native functions of a `World`. This needs to be fixed in some way.

Currently, `Broadcaster` only provides some sugar for `World`.

**Comment by Emilgardis** [comment]
cc @nchashch

**Comment by nchashch** [comment]
It would still be impossible to add `System`s because it would require a `Planner` that needs to own the `World`, so it won't be possible to move the `World` from `Broadcaster` while calling `Planner::new()`. And I am not sure if there are use cases for exposing resource creation, access functionality.

I also think that it would make sense to keep entities in `Broadcaster` read only, since they represent events and it adds the guarantee that the event you publish will be the same event when it is polled.
