### ISSUE TITLE
MouseCenterLockSystem does not work on osx.

### ISSUE THREAD

**Issue by Rhuagh** [amethyst/amethyst#754]
There are two issues with it:

* It positions the cursor at the the wrong place, this is likely caused by inconsistencies with hidpi screens in the winit API. If I divide the screen dimensions by 4 instead of 2 it works, which is consistent with my screen (hidpi = 2).
* `set_cursor_position` generate device events on osx, which cause the camera to always "go back" to the starting position whenever you try to move it. I'm not sure if this is an error in winit, or a feature. Also not sure how to get around it. 

Swapping `MouseCenterLockSystem` for `CursorHideSystem` makes both the `fly_camera` and `arc_ball_camera` examples work beautifully. With `MouseCenterLockSystem` none of them work very well.

**Comment by Xaeroxe** [comment]
> set_cursor_position generate device events on osx, which cause the camera to always "go back" to the starting position whenever you try to move it. I'm not sure if this is an error in winit, or a feature. Also not sure how to get around it.

Any platform inconsistency in winit is a bug imo.  That being said I don't have an easy fix for this, nor do I know how it should be fixed.  Pinging @francesca64 for her opinion on this.

**Comment by francesca64** [comment]
I'm currently working on implementing consistent HiDPI behavior on all backends (https://github.com/tomaka/winit/issues/105#issuecomment-389330207); X11, Windows, and macOS are already more or less done, so the first problem will be fixed soon enough. HiDPI is the "killer feature" of winit 0.16, which means it will kill every single thing that exists downstream with really tedious breaking API changes.

For the second problem, well, which `DeviceEvent` are you getting? I'm not seeing `MouseMotion` (or `WindowEvent::CursorMoved`, for that matter). `set_cursor_position` really shouldn't be generating an event, since it uses [`CGWarpMouseCursorPosition`](https://developer.apple.com/documentation/coregraphics/1456387-cgwarpmousecursorposition?language=objc).

(Also, `set_cursor_position` and `WindowEvent::CursorMoved` seem to be relative to the entire window rather than to the client area. I'd better fix that too.)

While we're on the topic of cursors, if you don't want me to destroy `CursorState` this is the place to stop me: tomaka/winit#537

**Comment by Xaeroxe** [comment]
This issue might be closed by #755 soon, however I'd still like to resolve @francesca64 's event questions @Rhuagh .

**Comment by Rhuagh** [comment]
If I use our `MouseCenterLockSystem`, which use `set_cursor_position` to set the cursor to the center of the window, and then run that and just do a swipe on the touchpad in a short diagonal towards the lower right corner I get this:

```
Motion event: MouseMotion { delta: (-76.0, -68.0) }
Motion event: MouseMotion { delta: (0.0, 8.0) }
Motion event: MouseMotion { delta: (6.0, 2.0) }
Motion event: MouseMotion { delta: (12.0, 22.0) }
Motion event: MouseMotion { delta: (36.0, 42.0) }
Motion event: MouseMotion { delta: (46.0, 64.0) }
Motion event: MouseMotion { delta: (32.0, 40.0) }
```

**Comment by francesca64** [comment]
Oh, well that's not surprising. `set_cursor_position` isn't generating those events, rather, you swiping the touchpad is generating them.

**Comment by Rhuagh** [comment]
In one direction yes, but why am I getting events for the reverse direction?

**Comment by Rhuagh** [comment]
https://expirebox.com/download/abcdf3f6c5d807d89f0c676e5c87381a.html

Check that video, you can see when I make really really small movements the camera kind of bounce back, which it doesn't if i only remove the `set_cursor_position` calls.

**Comment by francesca64** [comment]
Ah, I see. I'm too busy to fix that now, but if you report an issue to winit I won't forget.

**Comment by Rhuagh** [comment]
I'll make a note to create a more selfcontained example that demonstrates the issue
