### ISSUE TITLE
PointLights can only be expressed using global coordinates

### ISSUE THREAD

**Issue by aejt** [amethyst/amethyst#782]
When rendered using the shaded pass, the positions of PointLights are expressed in global coordinates and thus are independent from the entity's GlobalTransform. Either removing the PointLight's position and only depending on GlobalTransforms or having it be relative to the GlobalTransform would make a lot more sense.

**Comment by omni-viral** [comment]
Position should be relative to `GlobalTransform`

**Comment by Rhuagh** [comment]
Is there a reason not to use only the `GlobalTransform` directly?

**Comment by omni-viral** [comment]
One object can have mesh and light with shifted origins.
No reason to make it 3 objects.

**Comment by Rhuagh** [comment]
Well, true I guess, but it's also a bit confusing as a user to know when to use what, when should I be using `Transform` and when an attribute on `Mesh`, `Light` etc. We are essentially duplicating hierarchy information by doing it this way.

**Comment by omni-viral** [comment]
We should document it.
"Use non-zero position for `Mesh` `Light` when you want to make it appear shifted from `Entity`s origin."

**Comment by minecrawler** [comment]
My 2 cents (I might be wrong though, since I am struggling with all the changes you add to Amethyst all the time):

1. What I find a bit confusing is that light sources use `[f32; 3]` for position, while `Mesh` has a `Matrix4<f32>` transform field.
2. I really like that we can shift meshes and lights from the entity's position, however it still is a very simplistic form of grouping. Let's say for example I want to dynamically group game objects in a hierarchy. Say you have a parrot mesh. It can fly around on its own, but it can land on a pirate mesh's shoulder and should then be grouped with the pirate mesh. However, the pirate might go aboard his pirate ship. So then I have a hierarchy like this:

```
world
  ├ ...
  ├ pirate ship
  │    ├ ...
 ...   ├ pirate
       │    ├ ...
      ...   ├ parrot
            │    ├ ...
           ...  ...
```

AFAIK that's not possible with today's Amethyst and traditionally is solved using a scene graph. But is a scene graph the right thing to do using an ECS? How can we optimize for hierarchical dependencies in an ECS? (My idea: create a scene graph and store entities on the nodes and a way to customize how components should be added up, implementing default behavior for (Global)Transform).

If we solve that question, then a Light does not need a position, because it can use the Transform on the entity.

**Comment by Rhuagh** [comment]
@minecrawler We definitely have scene graph support in amethyst, by way of a `Parent` tree.

**Comment by Rhuagh** [comment]
A point light have a position as a translation only because it has no direction.

**Comment by minecrawler** [comment]
Ok, so we have `Parent`s. Then why not use that to control the position and use a transform struct directly as a component on the light's entity? Having so many ways to do the same thing is confusing.

**Comment by Rhuagh** [comment]
That was the question I asked :)

**Comment by torkleyy** [comment]
:+1: on using multiple entities for multiple positions.

**Comment by torkleyy** [comment]
Note for new contributors: This should be very easy to fix. The only thing you need to do is remove the position from the light and its occurrences. Feel free to ask for help anytime!

**Comment by Rhuagh** [comment]
And make the passes use `GlobalTransform` when sending data to the GPU.

**Comment by omni-viral** [comment]
Then remove transform from `Mesh` as well.
