### ISSUE TITLE
Status of glTF import?

### ISSUE THREAD

**Issue by jondo2010** [amethyst/amethyst#788]
what's the priority and difficulty of this one?

**Comment by Rhuagh** [comment]
I would wait a few days to analyze this. The GLTF importer is being completely rewritten basically. 
Technically, after the next lines of PRs are merged, we will support everything except:

* Camera
* Morph targets
* Extensions

**Comment by Rhuagh** [comment]
The new example is a lot better, we got a new original art piece which use the PBR system with transparency.

**Comment by torkleyy** [comment]
If we manage to load https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza that would already be a cool demo I think. Definitely suitable for showing our renderer.

**Comment by jojolepro** [comment]
Status?

**Comment by anderejd** [comment]
Here's the example I tried to get working in #877 <http://github.khronos.org/glTF-WebGL-PBR/> (the live demo currently loads the "DamagedHelmet" reference sample as default)

I removed that experiment from #877 since it was a bit too ambitious for me right now, and it was suggested by Rhuagh. Regarding that those sample models though, would it be a good direction for Amethyst to support gltf 2.0 fully? in other words rendering the sample models the same way or close to the same as the reference implementation? (see the live demo link above).

**Comment by jojolepro** [comment]
I'm impressed by how that looks. Fully supporting a standard like gltf definitely looks like something that we want. The tip I can give you is to go by iterations, with a PR for each (or combining them if they are small). Adding the required features one by one until you get them all together.

Thanks!

**Comment by Rhuagh** [comment]
There are a few issues with the importer currently: 

* Material ids are just pure bugged, they should be removed
* Node names are not kept
* Joint ids/weights should be added (empty) for models that don't have them

Then there's missing support for a few things:

* Progressive jpeg (because non of the image crates supported it when the importer was created).
* Morph targets (hard)
* Cameras
* Extensions?

**Comment by anderejd** [comment]
@Rhuagh Thanks for the update! The progressive jpeg support should be ready to merge #877 as far as I know.

> I would wait a few days to analyze this. The GLTF importer is being completely rewritten basically.

Is this still in the works? Where are the related PRs? In forks? Can I assist?

**Comment by jojolepro** [comment]
I'm not aware of a current gltf importer rewrite, and rhuagh is taking a break from heavy developement from what I understood. Maybe we should just continue improving the current importer to fix the issues mentionned by Rhuagh yesterday.

**Comment by Rhuagh** [comment]
That was the prefab rewrite, that's been done for months now, sorry.

**Comment by torkleyy** [comment]
How much is left here? Is the TODO list still valid?

**Comment by Rhuagh** [comment]
I'm closing this, we can revisit the things that are not done individually at a later point (morph targets, cameras, lights), and if so we should create individual stories for each.
