### ISSUE TITLE
[RFC] Labeling entities

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#790]
I think we should start to give entities a `Name` / `Label` component. This can be useful

* in the editor
* for scene files
* for debugging

Unresolved: should the name be unique? Without uniqueness, using it for scene files wouldn't make a whole lot of sense, but we'd need some way to enforce it.

**Comment by minecrawler** [comment]
I am not sure that it always makes sense to label entities. Especially using an ECS, I don't really care about the individual entities most of the time... Taking a look at your use-cases, I cannot see a single relevant case for the release build of a game, and personally, I can only come up with a few; for example  in low-performance scenarios to not store a reference to every single "special" entity or when a marker-component is overhead for the dev. As such, I would not enforce labeling of entities, but make it optional. There should be a way to retrieve an entity by its name (for example "Player 1").

---

> should the name be unique?

imho, yes, definitely. Otherwise, labeling would not make a whole lot of sense and one could simply use a component and join.

> but we'd need some way to enforce it.

labeling could be done using a hashmap. If there is an entry at the location, reject the name. For programmatically called labeling methods, that might be a panic, since the dev does something wrong there. For an importer, it might be an `Err()`, since "the file is corrupt (multiple entities with the same name)."

**Comment by torkleyy** [comment]
Yeah, it's meant to be optional.

**Comment by Rhuagh** [comment]
Something like `Tag`  in utils? That is only type tagging though, so not really the same thing, but some like it atleast.

**Comment by torkleyy** [comment]
@Rhuagh this would also be useful for the prefab system so the entities could be a map rather than just a list. That would make specifying the parent a little nicer.

**Comment by jojolepro** [comment]
Name helps with:
-Editor scene organisation
-Runtime debugging

Name is bad for:
-Performance when using lots of entities (which is the point of having an ecs)

I think that having a name should be optionnal, and configured by entity. It would probably make sense to have just a Named component?

world.create_entity.with(Named("ball")) (standard)
world.create_entity.named("ball") (my preferred)
world.create_named_entity("ball") (opinions?)

**Comment by OvermindDL1** [comment]
> It would probably make sense to have just a Named component?

That's what I do.  Unsure why it would be done any other way?

**Comment by jojolepro** [comment]
I think we agreed on making a Named (or Label) optionnal component to name entities and to be able to access and visually recognize them.

Tasks:
* Create the component.
* Add a entity builder utility function .named("the_name")

**Comment by jojolepro** [comment]
*reserving this issue*
