### ISSUE TITLE
Keybind to ungrab the mouse: FlyCamera & ArcBallCamera

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#828]
Add a way to stop grabbing the mouse when using the FlyCamera or the ArcBallCamera.

**Comment by zoonage** [comment]
Moving discussion in #840 to here

@jojolepro Just so I can be sure I have the right requirements here; What we need is the following

1. A `MovementToggle` resource
2. A `MovementToggleSystem` that checks for some specific keypress events (? Is this correct and if so which one should they be?)
3. Finally (the bit that I'm confused about), how does this system interact with the `FlyMovementSystem` and the `ArcBallMovementSystem` to stop them moving? Is there an example somewhere of two systems interacting?

**Comment by zoonage** [comment]
@jojolepro A bucket load of questions incoming probably stemming from my complete lack of understanding of how the components/resources/systems all interact.

1. By remove from the camera do you mean remove it from the `Entity`? I.e. do the reverse of `ControlTagPrefab::load_prefab`? I'm unsure how that would be done since I can't pass an `Entity` around as `SystemData` to remove it from the `WriteStorage<'a, FlyControlTag>` or `WriteStorage<'a, ArcBallControlTag>`.

2. How can the toggling be done in the state? Would the `GrabCursorOnFocus` be added to the world as a resource by the state? Would we then need a system that checks for when this resource is added to then;
    1. Send "some event" to `CursorHideSystem` to tell it to release the cursor via the `amethyst_renderer::release_cursor` function. Since `CursorHideSystem` only responds to winit::Events` how can we trigger anything in it unless all the logic is handled inside the `CursorHideSystem`?
    2. Trigger the event described in question 1.

**Comment by jojolepro** [comment]
Partially fixed by this: https://github.com/amethyst/amethyst/pull/946/files
All that is left to do is to add this line to the amethyst rotation system
https://github.com/jojolepro/amethyst-extra/blob/cd1aa58cc5ad9e20bb4ac0bec672a9c959419e9a/src/lib.rs#L1306
