### ISSUE TITLE
Sprite Render Pass and Sprite Animation

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#829]
I propose a new render pass with its own shaders specifically for rendering sprites.

## Motivation

The current way sprites are drawn requires consumers to create and attach the following components:

```rust
let material = // Material { albedo: <texture>, ..MaterialDefaults.0.clone() }
let mesh = // either use the `with_sprite` helper, or make your own

let entity = world.create_entity()
    .with(mesh_handle)
    .with(material)
    .with(global_transform)
    .build();
```

This usage interface is unergonomic for at least the following reasons:

* **Boilerplate:** The `Material` concept isn't used except to be an adaptor to the 3D rendering interface
* **Partial objects:** Need to create two objects for one purpose
* **Animation:** Sprites with different dimensions need the mesh to mutate in sync with the material

## Proposal

Provide another render pass that removes the need for users to write their own boilerplate, but still achieves the same result.

## How

Some of this is based on guidance from @omni-viral in the gitter chat.

* Write shaders to draw two triangles for the sprite and map the texture coordinates.
* Write a render pass that wires through the sprite information for each entity to the shaders.
* Provide a `Component` that allows the render pass to work out the following:
    - which texture
    - sprite layout information (sprite dimensions, the sprite's texture coordinates)

Sprite animation will be mutation of the said `Component`, which means the texture and layout information all mutate at the same time.

## Tasks

* [x] experiment (#830)
* [x] sprite offsets
* [x] sprite mirroring
* [x] sprite animation

## Bikeshedding

Thing | Current name(s) | Proposed
--- | --- | ---
Render passes | `DrawSprite`, `DrawSpriteSeparate` |
Component | `SpriteRender` |
Vertex shader | `sprite.glsl` |
Fragment shader | `sprite.glsl` |
... | ... | ...

## Alternatives

Some of these are not mutually exclusive:

* Do nothing (always an option =p).
* Provide other `Component` types to make it more ergonomic to still use the `DrawFlat` pass (but probably makes `DrawFlat` unmaintainable)
* Provide another animation type that animates both `Material` and `Mesh` together

**Comment by omni-viral** [comment]
Texture shouldn't be changed during animation. Only texture coordinates.

**Comment by azriel91** [comment]
Hm, I've got a use case where bigger sprites are on a separate texture, and the game configuration allows a character to choose a different sprite sheet mid sequence. How should that be handled?

**Comment by omni-viral** [comment]
Well. This is possible but seems sub-optimal. Why can't you load it into one texture?

**Comment by azriel91** [comment]
> Why can't you load it into one texture?

Can it be done programmatically? (I guess roundabout question is, "is merging two images into one texture already implemented")
I'm intending for people who only have free graphics tools (e.g. MS Paint / paint.net) to be able to make sprites for the game I'm making, and so to make it easier for them, each sprite sheet contains static sprite dimensions<sup>1</sup>. It is possible to restrict every sequence to come from the same sprite sheet, but it's a surprise / not very ergonomic.

<sup>1</sup> as opposed to apps that export the texture coordinates when they assemble sprites for example

**Comment by omni-viral** [comment]
I'm no expert in sprites. Is it common for sprites from one spritesheet to have different dimensions?
You would have to implement loading for spritesheet. There you probably can merge images into single texture.

**Comment by karroffel** [comment]
I would also propose to add Batching from the beginning, for PoC it's not that important of course, but for example in Godot, the lack of batching bites some users in their butts - quite often. The renderer wasn't made with that in mind.

Here with Amethyst, it could be good if you do the 2D rendering in such a way from the beginning.

------

# Ideas:

 - Unless on tiled-renderers (mobile), splitting the sprites into "potentially has alpha" and "is opaque or has alpha cutoff" could be useful to separate the input into things that can use depth test and things that need alpha blending.

 - use instanced rendering instead of issuing one draw call for each texture

 - preparing a TextureAtlas that contains all the images for the current batch, probably it's good to write specific Sprites into the atlas and not the spritesheet, but that could become a VRAM bandwidth issue if sprites are changing a lot. Maybe some caching can be done to see which Sprites change a lot and which stay mostly static and then batch those all together.

 - prepare a primitive buffer that contains matrices and TextureAtlas UVs for the appropriate sprite.

---------

I don't know exactly how `gfx` handles instanced rendering and what hardware you are targeting primarily (GLES2 doesn't support instanced rendering but drivers optimize for certain command sequences (but still no primitive buffer support without hacking around with textures etc) so there's workarounds)

-------

Either way, nice to see some love for 2D :)

**Comment by omni-viral** [comment]
I like the idea of batching sprites that are used together.
One can treat atlas the same way it treats memory. Allocating regions from it for required sprites and freeing regions occupied by sprite that is no longer needed. Probably with LRU cache.

> become a VRAM bandwidth issue if sprites are changing a lot

How exactly sprites can change apart from being replaced with another one? In this case there is no difference because you need to load new pixels into some image region anyway. It could be the same atlas.

**Comment by omni-viral** [comment]
@karroffel Uploading new sprite to the GPU is slow. So you don't want to do this each frame ofc.
You even don't want to do this during the frame this new sprite is required. Better predict what sprites you'll need anyway.
And still there is no difference if you split into short-term and long-term atlases. It still can be single image. You just decide what to load: whole spritesheet or single sprite.

**Comment by azriel91** [comment]
> Is it common for sprites from one spritesheet to have different dimensions?

I don't know, but it certainly wouldn't be in my game,

> I would also propose to add Batching from the beginning

Wow, just looked it up and it looks cool (I'm a complete rookie at gamedev, so most things people say are new concepts). For others equally as new, watch [this video](https://www.codeandweb.com/what-is-a-sprite-sheet-performance).

Shall try to not code this into a corner so that it's not hard to add in later.

> You would have to implement loading for spritesheet. There you probably can merge images into single texture.

Scouting round for libraries, there's [`texture_packer`](https://github.com/PistonDevelopers/texture_packer) from piston developers, and [`rect_packer`](https://github.com/kryptan/rect_packer) which is a fork of texture_packer with modifications, but I'm not sure what they are.

**Comment by omni-viral** [comment]
> not sure what they are.

Looks like [`rect_packer`](https://github.com/kryptan/rect_packer) implements 2d packing solver to pack multiple rects into one big rect as tight as possible. This is what you need to fill texture atlas with images

**Comment by azriel91** [comment]
[`texture_packer`](https://github.com/PistonDevelopers/texture_packer) looks to be well suited - each sprite (including on a sprite sheet) can be packed by providing each sprite as a [`SubImage`](https://docs.rs/image/0.19.0/image/struct.SubImage.html), and it'll trim the transparent pixels away for you.

I better stop looking too far ahead -- should get the basic sprite animation working first.

**Comment by jojolepro** [comment]
I just want to make sure you know we already have sprite loading via the types Sprite SpriteRenderData entitybuilder.with_sprite.

**Comment by jojolepro** [comment]
It seems you do ;)

**Comment by Moxinilian** [comment]
How do you plan on handling sprite ordering? It is especially crucial in a 2D isometric context for example.

**Comment by jojolepro** [comment]
Normally handled by the `Transparent` component and enabling transparency for the pass.

**Comment by omni-viral** [comment]
@jojolepro I guess @Moxinilian asks about how the pass will make sprites in front to covert spites at the back and not vice versa.
I'd say that either you have to
* sort sprites before issue drawing
* position them in 3D

I use the second approach in it works great for isometry.
I setup isometric camera that translate position of objects in typical 3D world to isometric view (no perspective) and draw sprites at the resulting position.

**Comment by jojolepro** [comment]
Merged! Thanks!
