### ISSUE TITLE
Random notes about book sections

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#870]
* [ ] Expand https://www.amethyst.rs/book/develop/concepts/world.html#check-if-the-entity-was-deleted

Would be useful to have some information about when the deletion gets applied (at maintain).

* [ ] Fix code in https://www.amethyst.rs/book/develop/concepts/world.html#exec

Code looks odd, where does the `Result` come from? (plus: avoid `expect` in docs)

* [ ] Add explanation about growth in https://www.amethyst.rs/book/develop/concepts/event-channel.html

Just say that we track the ids and grow the channel if somebody didn't read the old events (-> importance of reading the events every frame).

---

This issue could be a "good first issue" if somebody would expand on my comments and explain them in detail.

**Comment by azriel91** [comment]
Leaving this random cheat sheet here since it's also doc related:

**Amethyst Cheat Sheet**

* Entity: An ID of a "thing", like a car. An entity may have `Component`s attached to it
* Component: An "attribute" of an entity, like "color".
* `World`: a big container of "resources".
* Resources: Any type. e.g. `MyStruct`

    There are many built in resources.
    
    - `EntitiesRes` stores "entities" (an ID and a "generation").
    - Component storages 

* System: A thing that operates on resources.
* Component storage:

    Keep track of the components for the entities that have it, e.g.

    - the color component storage keeps track that "entity E1 has color: black"
    - the position component storage keeps track that "E1 has xyz something, E2 has xyz something else"

    Inside a `System`, you can call `(color_storage, position_storage).join()`, and you will be operating on entities that have both a color and a position.

* Bundle: A grouping of systems to handle one "feature", e.g. `UiBundle` provides a number of UI related `System`s.
* Dispatcher: A grouping of `System`s that all run (which mutate the `World`), with dependency ordering info. e.g. you have all the UI systems, gameplay systems, all added into the dispatcher, and you call `dispatcher.update(..)`.
* GameData: A grouping of dispatchers that can be shared by different `State`s
* State: A particular state in the game, e.g. "menu selection", "game play"
* Application: Define's the initial `State`, and the bundles in the `GameData`.

**Comment by jojolepro** [comment]
By @torkleyy 


> _Note: Please however keep in mind that `Write` is still preferable to interior mutability, such as `Mutex` or `RwLock` for example.
> \_Note: Please however keep in mind that `Write` is still preferable to interior mutability, such as `Mutex` or `RwLock` for example.
> 
> Unrelated to this PR, but this line doesn't make sense. Write is interior mutability. Maybe this should be "preferable locks"? And then, there are cases where locks actually are preferable (we do use them for a few things).

**Comment by jojolepro** [comment]
fixed by #881
