### ISSUE TITLE
[Brainstorm] Asset Management and Pipeline: User Stories

### ISSUE THREAD

**Issue by VermillionAzure** [amethyst/amethyst#883]
A list of user stories that can be related to https://github.com/amethyst/amethyst/issues/875 will be maintained below.

### Template
```
As a <USER_TYPE>, I want to be able to <DO ACTION/USE CAPABILITY> so <REASON/RATIONALE>.
```

# User Stories

## Asset Pipelines/Management

- As a developer who wants a tight test/edit loop, I want to be able to dynamically update my game assets (e.g. sprites) at runtime by editing a file or performing an edit so that I can see the effects of my changes immediately without needing an extra compilation/restart step.

- As a continuous developer, I want to be able to have my assets automatically loaded by my application so that I don't have to.

- As a developer/QA person who is security-minded, I want to be able to check my static assets for undesired traits by allowing arbitrary checker programs to run on my assets at pipeline-build-time so that I don't have to do it manually and invariants I want to hold can be detected effortlessly.

- As a developer, I want to be able to query my asset management system for specific assets because ***IDK***.

**Comment by Ratysz** [comment]
(I'm assuming more stories are welcome?)

As a developer who likes neat distributions (in part for game jam purposes), I want to be able to load my assets from a `&[u8]`, so that I can use `include_bytes!()` to embed them into the executable. This doesn't have to be performant, because project scale is usually small.

**Comment by jojolepro** [comment]
@Ratysz that is exactly what `Format` does.

**Comment by kabergstrom** [comment]
Game developer can be non-coder in the following text.

- As a coder I want my asset importing and processing code to only have to care about the type of asset rather than asset source format specifics.
- As a game developer I want to be able to change asset import or asset build parameters without changing code or recompiling. 
- As a coder I want to be able to write asset preparation code in multiple stages: before & after asset import, before & after asset build, before & after asset edits by user.
- As a coder I want to be able to write static analysis passes on assets to enforce rules for content creators.
- As a game developer I want to be able to configure asset build parameters depending on build configuration and target platform.
- As a game developer I want the build and import process to be scalable and use all my hardware resources. If it can scale across multiple machines, even better!
- As a game developer I don't want to wait for assets to build after making a change that I want to test
- As a game developer I never want to lose work I've done on assets
- As a game developer I want to see changes I make be applied in a running game immediately, even over the network
- As a game developer I want to search my asset library to find what I'm looking for
- As a game developer I want to move or rename my files without breaking my game
- As a game developer I want to be able to control which assets get built and packaged for a specific target platform.
- As a game developer I want to create prefabs that can reference other prefabs and have dependencies be built, loaded and packaged automatically to ensure prefabs I want to include in a packaged game work, without having to specify all of them somewhere. _example: I want to build my game to load a specific scene on startup and have all dependencies be packaged automatically_
- As a coder I want to be able to customize how assets are packed on disk in a final build to improve loading time
- As a game developer I want to upgrade Amethyst when new versions come out without losing data
- As a game developer I rarely want to restart my tools to observe changes, and I never want to recompile unless I'm changing engine behaviour

**Comment by eaglgenes101** [comment]
As a developer prototyping game mechanics, I want to synthesize sprites at runtime or draw shapes without a backing sprite/model so I can visualize entity components without having to draw up corresponding sprites or meshes in the display system. 

(Maybe this is already implemented and I'm not peering far enough?)

**Comment by jojolepro** [comment]
You can.
First you create the mesh and attach the MeshHandle on your entity. (you create it using loader.load and/or genmesh)

Then, you create a Material from a TextureHandle. TextureHandle can be created using loader and a simple color.
loader.load_from_data with [0.5,0.2,0.3,1.0].into() as the color parameter (change the color value).

**Comment by omni-viral** [comment]
* As a gamer, I want to be able to not wait for updates to be fully downloaded before I start playing.
* As a gamer, I want to be able to forget about criptic error messages related to missing/corrupted data. I want the engine to fix an issue automatically (on the fly if possible).

**Comment by fhaynes** [comment]
Closing this, as it seems to have served its purpose, and the RFC has been untouched for awhile.
