### ISSUE TITLE
Make the texture filtering API public

### ISSUE THREAD

**Issue by Moxinilian** [amethyst/amethyst#966]
Currently, there is no way to change the filtering for textures without manually importing gfx. This forces the textures to be displayed with nearest filtering, which usually makes games and demos look unimpressive.

We should find a way to expose that to the user, possibly in a backend agnostic way. At least exporting the 3 gfx types needed could also do the trick.

**This is especially needed for 2D stuff hence why it's important for 0.9**

**Comment by torkleyy** [comment]
Since there's work on a new rendering API and we currently use gfx only, I don't think a wrapper is necessary. I started off with a wrapper, but I ended up copying the gfx types and mapping them 1:1, which doesn't make much sense.

**Comment by torkleyy** [comment]
Another topic: should we change the default to linear (or better)?

**Comment by fuchsnj** [comment]
I don't have strong feelings about it, but here's my 2 cents:
I think the default should be something better than linear. It's more rare to want linear (nearest-neighbor) and picking something better would give a better first impression to users.
It also has the side-effect of making demos look better, since it probably doesn't make sense to add additional code to change the texture filtering, unless the demo is specifically about that.

**Comment by torkleyy** [comment]
Okay, so do you want us to go for `Anisatropic`? I'm a bit worried that the variant allows you to directly specifiy the level, usually that's something you want to set globally.
